# Generated by Django 5.0 on 2026-01-23 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('sales', '0023_switch_to_verification_workflow'),
        ('shops', '0002_shop_shop_photo_alter_shop_shop_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BadDebtWriteOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('write_off_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('write_off_date', models.DateTimeField(auto_now_add=True)),
                ('original_amount', models.DecimalField(decimal_places=2, help_text='Original bill total', max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, help_text='Amount already paid', max_digits=10)),
                ('write_off_amount', models.DecimalField(decimal_places=2, help_text='Amount being written off', max_digits=10)),
                ('reason', models.CharField(choices=[('shop_closed', 'Shop Permanently Closed'), ('owner_deceased', 'Shop Owner Deceased'), ('bankruptcy', 'Bankruptcy/Insolvency'), ('legal_failed', 'Legal Collection Failed'), ('aged_debt', 'Aged Debt (180+ days)'), ('fraud', 'Fraud/Dispute'), ('other', 'Other Reason')], max_length=50)),
                ('detailed_notes', models.TextField(help_text='Detailed explanation for write-off')),
                ('approval_status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if rejected', null=True)),
                ('executed', models.BooleanField(default=False, help_text='Whether write-off has been executed')),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('bill_updated', models.BooleanField(default=False, help_text='Whether bill was updated')),
                ('shop_balance_updated', models.BooleanField(default=False, help_text='Whether shop balance was updated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_write_offs', to=settings.AUTH_USER_MODEL)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='write_offs', to='sales.bill')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_write_offs', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='write_offs', to='shops.shop')),
            ],
            options={
                'verbose_name': 'Bad Debt Write-Off',
                'verbose_name_plural': 'Bad Debt Write-Offs',
                'db_table': 'bad_debt_write_offs',
                'ordering': ['-write_off_date'],
            },
        ),
    ]
