# Generated by Django 6.0 on 2026-01-23 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_baddebtwriteoff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreditNote',
        ),
    ]
