# Generated by Django 6.0 on 2026-01-23 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_credit_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentReconciliation',
        ),
    ]
