# Generated by Django 5.0 on 2026-01-31 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_rename_to_sales_account_settlement'),
        ('shops', '0002_shop_shop_photo_alter_shop_shop_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesaccountsettlement',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='shops.shop'),
        ),
    ]
