# Generated by Django 5.0 on 2026-01-31 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_salesaccountsettlement_shop'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesaccountsettlement',
            name='cheque_collected',
            field=models.BooleanField(default=False, help_text='Physical cheque collected from rep'),
        ),
        migrations.AddField(
            model_name='salesaccountsettlement',
            name='collected_at',
            field=models.DateTimeField(blank=True, help_text='When cheque was collected', null=True),
        ),
        migrations.AddField(
            model_name='salesaccountsettlement',
            name='collected_by',
            field=models.ForeignKey(blank=True, help_text='Office staff who collected the cheque', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_cheques', to=settings.AUTH_USER_MODEL),
        ),
    ]
