# Generated by Django 6.0 on 2026-02-12 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_salesaccountsettlement_cheque_collected_and_more'),
        ('shops', '0004_shopphotohistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='baddebtwriteoff',
            name='customer_name',
            field=models.CharField(blank=True, help_text='For unregistered customer write-offs', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='baddebtwriteoff',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='write_offs', to='shops.shop'),
        ),
    ]
