import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'zergo_sales.settings')
django.setup()

from django.db import connection

cursor = connection.cursor()

# Create missing tables
print("Creating missing payment tables...")

# old_payments
cursor.execute("""
CREATE TABLE IF NOT EXISTS "old_payments" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "payment_number" varchar(50) NOT NULL UNIQUE,
    "payment_date" timestamp with time zone NOT NULL,
    "payment_method" varchar(20) NOT NULL,
    "amount" numeric(10, 2) NOT NULL,
    "reference_number" varchar(100) NULL,
    "bank_name" varchar(100) NULL,
    "cheque_date" date NULL,
    "status" varchar(20) NOT NULL,
    "is_provisional" boolean NOT NULL,
    "notes" text NULL,
    "attachment" varchar(100) NULL,
    "verified_at" timestamp with time zone NULL,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "bill_id" bigint NULL,
    "received_by_id" bigint NULL,
    "return_ref_id" bigint NULL,
    "shop_id" bigint NOT NULL,
    "verified_by_id" bigint NULL
)
""")
print("✓ old_payments table created")

# credit_notes
cursor.execute("""
CREATE TABLE IF NOT EXISTS "credit_notes" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "credit_note_number" varchar(50) NOT NULL UNIQUE,
    "credit_note_date" timestamp with time zone NOT NULL,
    "amount" numeric(10, 2) NOT NULL,
    "reason" text NOT NULL,
    "is_applied" boolean NOT NULL,
    "applied_date" timestamp with time zone NULL,
    "created_at" timestamp with time zone NOT NULL,
    "bill_id" bigint NULL,
    "created_by_id" bigint NULL,
    "shop_id" bigint NOT NULL
)
""")
print("✓ credit_notes table created")

# payment_attachments
cursor.execute("""
CREATE TABLE IF NOT EXISTS "payment_attachments" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "file" varchar(100) NOT NULL,
    "description" varchar(200) NULL,
    "uploaded_at" timestamp with time zone NOT NULL,
    "payment_id" bigint NOT NULL
)
""")
print("✓ payment_attachments table created")

print("\n✅ All payment tables created successfully!")
