# Generated by Django 6.0 on 2026-02-25 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalCaseValueSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_value', models.DecimalField(decimal_places=2, help_text='Price per case (e.g., 2160.00)', max_digits=10)),
                ('effective_date', models.DateField(help_text='Date when this case value becomes effective')),
                ('is_active', models.BooleanField(default=True, help_text='Only one setting should be active at a time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='global_case_value_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Global Case Value Setting',
                'verbose_name_plural': 'Global Case Value Settings',
                'db_table': 'global_case_value_settings',
                'ordering': ['-effective_date'],
            },
        ),
    ]
