# Generated by Django 6.0 on 2026-01-27 16:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_salesreplocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.TextField(help_text='Reason for requesting advance')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount approved (may differ from requested)', max_digits=12, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank Transfer'), ('adjustment', 'Adjustment')], max_length=20, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_advances', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advance_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Advance Request',
                'verbose_name_plural': 'Advance Requests',
                'db_table': 'advance_requests',
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='UserMoneyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Starting balance when account created', max_digits=12)),
                ('opening_date', models.DateField(default=django.utils.timezone.now, help_text='Date account was created')),
                ('opening_notes', models.TextField(blank=True, help_text='Notes about opening balance', null=True)),
                ('total_credited', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount added to account (commissions, bonuses, etc)', max_digits=12)),
                ('total_debited', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount paid out to user', max_digits=12)),
                ('total_advance_given', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total advances given (money given before earning)', max_digits=12)),
                ('total_advance_recovered', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total advance recovered from earnings', max_digits=12)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current balance - Positive = We owe user, Negative = User owes us (advance)', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_money_accounts', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='money_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Money Account',
                'verbose_name_plural': 'User Money Accounts',
                'db_table': 'user_money_accounts',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='MoneyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit - Add Money'), ('debit', 'Debit - Remove Money'), ('commission_payment', 'Commission Payment'), ('bonus', 'Bonus Payment'), ('payment', 'Payment to User'), ('advance_given', 'Advance Given'), ('advance_recovery', 'Advance Recovery'), ('adjustment_credit', 'Adjustment (Credit)'), ('adjustment_debit', 'Adjustment (Debit)')], max_length=30)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank Transfer'), ('adjustment', 'Adjustment')], max_length=20, null=True)),
                ('reference_number', models.CharField(blank=True, help_text='Cheque number, bank ref, receipt number, etc.', max_length=100, null=True)),
                ('description', models.CharField(help_text='Brief description of transaction', max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('commission_reference', models.CharField(blank=True, help_text='Commission month/period reference (e.g., 2026-01)', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advance_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounts.advancerequest')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_money_transactions', to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='accounts.usermoneyaccount')),
            ],
            options={
                'verbose_name': 'Money Transaction',
                'verbose_name_plural': 'Money Transactions',
                'db_table': 'money_transactions',
                'ordering': ['-transaction_date', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='advancerequest',
            index=models.Index(fields=['user', '-request_date'], name='advance_req_user_id_e5508c_idx'),
        ),
        migrations.AddIndex(
            model_name='advancerequest',
            index=models.Index(fields=['status'], name='advance_req_status_c11515_idx'),
        ),
        migrations.AddIndex(
            model_name='usermoneyaccount',
            index=models.Index(fields=['user'], name='user_money__user_id_3f1760_idx'),
        ),
        migrations.AddIndex(
            model_name='usermoneyaccount',
            index=models.Index(fields=['is_active'], name='user_money__is_acti_c54923_idx'),
        ),
        migrations.AddIndex(
            model_name='moneytransaction',
            index=models.Index(fields=['account', '-transaction_date'], name='money_trans_account_0d8a15_idx'),
        ),
        migrations.AddIndex(
            model_name='moneytransaction',
            index=models.Index(fields=['transaction_type'], name='money_trans_transac_dc2331_idx'),
        ),
        migrations.AddIndex(
            model_name='moneytransaction',
            index=models.Index(fields=['transaction_date'], name='money_trans_transac_5e6468_idx'),
        ),
    ]
