# Generated by Django 6.0 on 2026-02-23 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_advancerequest_usermoneyaccount_moneytransaction_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_platform_admin',
            field=models.BooleanField(default=False, help_text='Platform super-admin who can manage all distributors'),
        ),
        migrations.AddField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='The distributor this user belongs to. Null for platform super-admins.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='tenants.distributor'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('office', 'Distributor'), ('sales_rep', 'Sales Representative')], default='sales_rep', max_length=20),
        ),
    ]
