# Generated by Django 6.0 on 2025-12-30 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_oldpayment_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.CharField(choices=[('cheque_front', 'Cheque Front'), ('cheque_back', 'Cheque Back'), ('bank_receipt', 'Bank Transfer Receipt'), ('other', 'Other')], max_length=20)),
                ('image', models.ImageField(upload_to='payment_receipts/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='payments.oldpayment')),
            ],
            options={
                'db_table': 'payment_attachments',
                'ordering': ['attachment_type', 'uploaded_at'],
            },
        ),
    ]
