# Generated by Django 6.0 on 2026-01-02 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paymentattachment'),
        ('sales', '0008_return_applied_amount_return_is_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldpayment',
            name='return_ref',
            field=models.ForeignKey(blank=True, help_text='Return used for this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_applications', to='sales.return'),
        ),
        migrations.AlterField(
            model_name='oldpayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank Transfer'), ('credit', 'Credit'), ('return_adjustment', 'Return Adjustment')], max_length=20),
        ),
    ]
