# Generated by Django 6.0 on 2026-01-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_oldpayment_return_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldpayment',
            name='is_provisional',
            field=models.BooleanField(default=False, help_text='Payment using pending return - awaiting approval'),
        ),
    ]
