# Generated by Django 6.0 on 2025-12-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_photo',
            field=models.ImageField(blank=True, null=True, upload_to='shop_photos/'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
