# Generated by Django 5.0 on 2026-01-31 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_shop_shop_photo_alter_shop_shop_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.IntegerField(choices=[(1, 'Level 1 - View Only (List & Map)'), (2, 'Level 2 - Standard Access (Activities)'), (3, 'Level 3 - Full Access (Unlimited)')], default=1, help_text='1=View Only, 2=Standard, 3=Full Access')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_shop_access', to=settings.AUTH_USER_MODEL)),
                ('sales_rep', models.ForeignKey(limit_choices_to={'user_type': 'sales_rep'}, on_delete=django.db.models.deletion.CASCADE, related_name='shop_access_grants', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='shops.shop')),
            ],
            options={
                'verbose_name': 'Shop Access Grant',
                'verbose_name_plural': 'Shop Access Grants',
                'db_table': 'shop_access',
                'ordering': ['-access_level', '-granted_at'],
                'indexes': [models.Index(fields=['shop', 'sales_rep', 'is_active'], name='shop_access_shop_id_c451d9_idx'), models.Index(fields=['sales_rep', 'access_level'], name='shop_access_sales_r_62959d_idx')],
                'unique_together': {('shop', 'sales_rep')},
            },
        ),
    ]
