# Generated by Django 6.0 on 2026-01-31 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_shopaccess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopPhotoHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='shop_photos/history/%Y/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Current active photo')),
                ('notes', models.TextField(blank=True, help_text='Photo context or notes', null=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_history', to='shops.shop')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_shop_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shop Photo',
                'verbose_name_plural': 'Shop Photo History',
                'db_table': 'shop_photo_history',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['shop', 'is_active'], name='shop_photo__shop_id_45e477_idx'), models.Index(fields=['shop', '-uploaded_at'], name='shop_photo__shop_id_ce452d_idx')],
            },
        ),
    ]
