# Generated by Django 6.0 on 2026-02-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_shopphotohistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopvisit',
            name='visit_type',
            field=models.CharField(choices=[('manual', 'Manual Check-in'), ('auto_bill', 'Auto — Bill Created'), ('auto_payment', 'Auto — Payment Recorded'), ('auto_return', 'Auto — Return Created'), ('auto_exchange', 'Auto — Exchange Created')], default='manual', max_length=20),
        ),
    ]
