# Generated by Django 6.0 on 2026-02-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributorprofile',
            name='login_bg_image',
            field=models.ImageField(blank=True, help_text='Custom background image for login page (recommended 1920x1080px)', null=True, upload_to='business/login/'),
        ),
        migrations.AddField(
            model_name='distributorprofile',
            name='login_bg_style',
            field=models.CharField(choices=[('gradient', 'Brand Gradient'), ('solid', 'Solid Color'), ('image', 'Background Image')], default='gradient', help_text='Login page background style', max_length=10),
        ),
        migrations.AddField(
            model_name='distributorprofile',
            name='login_subtitle',
            field=models.CharField(blank=True, default='Sales Management System', help_text='Subtitle text shown on the login page below the business name', max_length=200),
        ),
        migrations.AddField(
            model_name='distributorprofile',
            name='navbar_icon',
            field=models.CharField(blank=True, default='fas fa-store', help_text='FontAwesome icon class for navbar brand (e.g., fas fa-store, fas fa-truck)', max_length=50),
        ),
        migrations.AddField(
            model_name='distributorprofile',
            name='navbar_style',
            field=models.CharField(choices=[('gradient', 'Gradient (Primary → Secondary)'), ('solid', 'Solid Primary Color'), ('dark', 'Dark (Dark Grey/Black)')], default='gradient', help_text='Visual style for the top navigation bar', max_length=10),
        ),
        migrations.AddField(
            model_name='distributorprofile',
            name='navbar_title',
            field=models.CharField(blank=True, help_text='Short name shown in the navbar (max 30 chars). Defaults to business name.', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='distributorprofile',
            name='sidebar_active_style',
            field=models.CharField(choices=[('line', 'Left Border Line'), ('fill', 'Filled Background'), ('pill', 'Rounded Pill')], default='line', help_text='Active menu item highlight style in the sidebar', max_length=10),
        ),
    ]
