# Generated by Django 6.0 on 2026-02-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_distributorprofile_login_bg_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributorprofile',
            name='navbar_brand_type',
            field=models.CharField(choices=[('logo', 'Company Logo'), ('icon', 'FontAwesome Icon')], default='logo', help_text='Show company logo or a FontAwesome icon next to the title', max_length=10),
        ),
    ]
