# Generated by Django 6.0 on 2026-02-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_add_navbar_brand_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributorprofile',
            name='login_brand_type',
            field=models.CharField(choices=[('logo', 'Company Logo'), ('icon', 'FontAwesome Icon')], default='logo', help_text='Show company logo or a FontAwesome icon on the login page', max_length=10),
        ),
    ]
