# Generated by Django 6.0 on 2026-02-24 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global Category',
                'verbose_name_plural': 'Global Categories',
                'db_table': 'global_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GlobalCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, unique=True)),
                ('company_code', models.CharField(max_length=20, unique=True)),
                ('tagline', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('contact_person', models.CharField(blank=True, default='', max_length=200)),
                ('phone_number', models.CharField(blank=True, default='', max_length=15)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('website', models.URLField(blank=True, default='')),
                ('address', models.TextField(blank=True, default='')),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(default='Sri Lanka', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='global_company_logos/')),
                ('logo_receipt', models.ImageField(blank=True, help_text='Logo optimized for thermal receipts (B&W, 200x80px)', null=True, upload_to='global_company_logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global Company',
                'verbose_name_plural': 'Global Companies',
                'db_table': 'global_companies',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='GlobalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(help_text='Global unique product code (e.g., MAX-ORG-500)', max_length=50, unique=True)),
                ('product_name', models.CharField(help_text='Full product name (e.g., Max Orange 500ml)', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('size', models.CharField(choices=[('220ML', '220ML'), ('250ML', '250ML'), ('500ML', '500ML'), ('750ML', '750ML'), ('1000ML', '1000ML (1L)'), ('1500ML', '1500ML (1.5L)'), ('2200ML', '2200ML (2.2L)')], default='500ML', max_length=20)),
                ('marked_price', models.DecimalField(decimal_places=2, default=0.0, help_text='MRP / Marked Retail Price (global, same everywhere)', max_digits=10)),
                ('bottles_per_pack', models.IntegerField(default=24, help_text='Bottles per pack/case')),
                ('barcode', models.CharField(blank=True, default='', max_length=50)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='global_products/')),
                ('display_order', models.IntegerField(default=0, help_text='Lower number appears first in lists')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Product category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.globalcategory')),
                ('company', models.ForeignKey(help_text='Brand/manufacturer', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.globalcompany')),
            ],
            options={
                'verbose_name': 'Global Product',
                'verbose_name_plural': 'Global Products',
                'db_table': 'global_products',
                'ordering': ['display_order', 'product_name'],
            },
        ),
    ]
