# Generated by Django 6.0 on 2025-12-21 22:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_sale_created_by_remove_sale_sales_rep_and_more'),
        ('sales', '0001_initial'),
        ('shops', '0002_shop_shop_photo_alter_shop_shop_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['-bill_date']},
        ),
        migrations.AlterModelOptions(
            name='return',
            options={'ordering': ['-return_date'], 'verbose_name': 'Return', 'verbose_name_plural': 'Returns'},
        ),
        migrations.AlterModelOptions(
            name='returnitem',
            options={'verbose_name': 'Return Item', 'verbose_name_plural': 'Return Items'},
        ),
        migrations.RemoveField(
            model_name='return',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='return',
            name='refund_status',
        ),
        migrations.AddField(
            model_name='billitem',
            name='foc_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Free of Charge quantity given to shop', max_digits=10),
        ),
        migrations.AddField(
            model_name='return',
            name='commission_adjusted',
            field=models.BooleanField(default=False, help_text='Deducted from rep commission'),
        ),
        migrations.AddField(
            model_name='return',
            name='commission_month',
            field=models.CharField(blank=True, help_text='YYYY-MM to deduct from', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='return',
            name='refund_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash Refund'), ('credit_note', 'Credit Note'), ('adjustment', 'Account Adjustment')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='return',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='sales_rep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='old_sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='return',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='return',
            name='return_number',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='return',
            name='sales_rep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='return',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='shops.shop'),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('sale_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sale_status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partially Paid'), ('paid', 'Paid')], default='unpaid', max_length=20)),
                ('delivery_status', models.CharField(choices=[('delivered', 'Delivered'), ('returned', 'Returned')], default='delivered', max_length=20)),
                ('vehicle_number', models.CharField(blank=True, max_length=20, null=True)),
                ('delivered_by', models.CharField(blank=True, help_text='Driver/Helper name', max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sales_rep', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='shops.shop')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
                'db_table': 'sales',
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_type', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank Transfer'), ('credit', 'Credit')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cheque_number', models.CharField(blank=True, max_length=50, null=True)),
                ('cheque_date', models.DateField(blank=True, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=200, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('collection_status', models.CharField(choices=[('pending', 'Pending Collection'), ('collected', 'Collected/Cleared'), ('bounced', 'Bounced/Failed')], default='pending', max_length=20)),
                ('collected_date', models.DateField(blank=True, help_text='Date when cheque cleared or credit collected', null=True)),
                ('commission_eligible', models.BooleanField(default=False, help_text='True when payment is collected (cash converted)')),
                ('commission_month', models.CharField(blank=True, help_text='YYYY-MM when eligible for commission', max_length=7, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collected_payments', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.sale')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.AddField(
            model_name='return',
            name='original_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='sales.sale'),
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('foc_quantity', models.DecimalField(decimal_places=2, default=0, help_text='Free of Charge quantity given to shop', max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(help_text='Flavor-specific product', on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale')),
            ],
            options={
                'verbose_name': 'Sale Item',
                'verbose_name_plural': 'Sale Items',
                'db_table': 'sale_items',
            },
        ),
        migrations.CreateModel(
            name='CommissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(help_text='YYYY-MM format', max_length=7)),
                ('total_sales_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total sales in month', max_digits=10)),
                ('collected_amount', models.DecimalField(decimal_places=2, default=0, help_text='Only collected payments', max_digits=10)),
                ('returns_amount', models.DecimalField(decimal_places=2, default=0, help_text='Returns in month', max_digits=10)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=5.0, help_text='Commission percentage', max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, help_text='(Collected - Returns) × Rate', max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sales_rep', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commission Record',
                'verbose_name_plural': 'Commission Records',
                'db_table': 'commission_records',
                'ordering': ['-month', 'sales_rep'],
                'unique_together': {('month', 'sales_rep')},
            },
        ),
    ]
