# Generated by Django 6.0 on 2025-12-25 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_bill_options_alter_return_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Template name (e.g., 'Standard Thermal', 'Detailed A4')", max_length=100)),
                ('paper_size', models.CharField(choices=[('thermal_48mm', 'Thermal 48mm'), ('thermal_58mm', 'Thermal 58mm'), ('thermal_80mm', 'Thermal 80mm'), ('a4', 'A4 Paper'), ('a5', 'A5 Paper'), ('letter', 'Letter Size')], max_length=20)),
                ('show_company_logo', models.BooleanField(default=True)),
                ('company_name', models.CharField(default='Zergo Distributors', max_length=200)),
                ('company_address', models.TextField(blank=True, null=True)),
                ('company_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('company_email', models.CharField(blank=True, max_length=100, null=True)),
                ('company_website', models.CharField(blank=True, max_length=100, null=True)),
                ('header_text', models.TextField(blank=True, help_text='Custom header text', null=True)),
                ('footer_text', models.TextField(blank=True, help_text="Custom footer text (e.g., 'Thank you for your business')", null=True)),
                ('show_barcode', models.BooleanField(default=False, help_text='Show bill number as barcode')),
                ('show_qr_code', models.BooleanField(default=False, help_text='Show QR code for digital receipt')),
                ('show_tax_breakdown', models.BooleanField(default=True)),
                ('show_discount_details', models.BooleanField(default=True)),
                ('show_payment_method', models.BooleanField(default=True)),
                ('show_sales_rep', models.BooleanField(default=True)),
                ('show_shop_location', models.BooleanField(default=True)),
                ('font_size_header', models.IntegerField(default=14)),
                ('font_size_body', models.IntegerField(default=10)),
                ('font_size_footer', models.IntegerField(default=8)),
                ('is_default', models.BooleanField(default=False, help_text='System default template')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bill Template',
                'verbose_name_plural': 'Bill Templates',
                'db_table': 'bill_templates',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BillSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_paper_size', models.CharField(choices=[('thermal_48mm', 'Thermal 48mm'), ('thermal_58mm', 'Thermal 58mm'), ('thermal_80mm', 'Thermal 80mm'), ('a4', 'A4 Paper'), ('a5', 'A5 Paper'), ('letter', 'Letter Size')], default='thermal_80mm', max_length=20)),
                ('default_printer_name', models.CharField(blank=True, help_text='Name of default printer', max_length=200, null=True)),
                ('auto_print', models.BooleanField(default=False, help_text='Auto-print after bill creation')),
                ('print_copies', models.IntegerField(default=1, help_text='Number of copies to print')),
                ('margin_top', models.IntegerField(default=5)),
                ('margin_bottom', models.IntegerField(default=5)),
                ('margin_left', models.IntegerField(default=5)),
                ('margin_right', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bill_settings', to=settings.AUTH_USER_MODEL)),
                ('default_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_users', to='sales.billtemplate')),
            ],
            options={
                'verbose_name': 'Bill Setting',
                'verbose_name_plural': 'Bill Settings',
                'db_table': 'bill_settings',
            },
        ),
    ]
