# Generated by Django 6.0 on 2025-12-30 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_billtemplate_billsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReturnItem',
        ),
        migrations.DeleteModel(
            name='Return',
        ),
    ]
