# Generated by Django 6.0 on 2025-12-31 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_remove_unused_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='settlement_method',
            field=models.CharField(choices=[('cash', 'Cash Refund'), ('credit_note', 'Credit Note'), ('next_bill', 'Adjust in Next Bill')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='returnitem',
            name='foc_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
