# Generated by Django 6.0 on 2026-01-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_return_settlement_method_returnitem_foc_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='applied_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount already applied to payments', max_digits=10),
        ),
        migrations.AddField(
            model_name='return',
            name='is_applied',
            field=models.BooleanField(default=False, help_text='Whether this return has been applied to a bill payment'),
        ),
    ]
