# Generated by Django 6.0 on 2026-01-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_return_settlement_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='field_cash_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount of cash given in field', max_digits=10),
        ),
        migrations.AddField(
            model_name='return',
            name='field_cash_given',
            field=models.BooleanField(default=False, help_text='Whether sales rep gave cash to customer in the field'),
        ),
        migrations.AddField(
            model_name='return',
            name='field_cash_given_at',
            field=models.DateTimeField(blank=True, help_text='When field cash was given', null=True),
        ),
        migrations.AddField(
            model_name='return',
            name='field_cash_notes',
            field=models.TextField(blank=True, help_text='Notes about field cash payment', null=True),
        ),
    ]
