# Generated by Django 6.0 on 2026-01-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_field_cash_settlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='field_receipt_number',
            field=models.CharField(blank=True, help_text='Field receipt number (FR) - temporary receipt before approval', max_length=50, null=True),
        ),
    ]
