# Generated by Django 5.0 on 2026-01-03 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_field_receipt_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billtemplate',
            options={'ordering': ['-is_default', 'receipt_type', 'name'], 'verbose_name': 'Bill Template', 'verbose_name_plural': 'Bill Templates'},
        ),
        migrations.AddField(
            model_name='billtemplate',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('si', 'Sinhala'), ('ta', 'Tamil')], default='en', help_text='Receipt language', max_length=5),
        ),
        migrations.AddField(
            model_name='billtemplate',
            name='qr_code_size',
            field=models.IntegerField(default=150, help_text='QR code size in pixels'),
        ),
        migrations.AddField(
            model_name='billtemplate',
            name='qr_code_type',
            field=models.CharField(choices=[('none', 'No QR Code'), ('verification', 'Receipt Verification URL'), ('website', 'Company Website'), ('payment', 'Payment Link')], default='none', help_text='Type of QR code to generate', max_length=20),
        ),
        migrations.AddField(
            model_name='billtemplate',
            name='receipt_type',
            field=models.CharField(choices=[('bill', 'Sales Bill/Invoice'), ('payment', 'Payment Receipt'), ('return', 'Return Receipt'), ('field_receipt', 'Field Cash Receipt')], default='bill', help_text='Type of receipt this template is for', max_length=20),
        ),
        migrations.AddField(
            model_name='billtemplate',
            name='thermal_cut_after_print',
            field=models.BooleanField(default=True, help_text='Auto-cut paper after printing'),
        ),
        migrations.AddField(
            model_name='billtemplate',
            name='thermal_feed_lines',
            field=models.IntegerField(default=3, help_text='Blank lines to feed before cutting'),
        ),
        migrations.AddField(
            model_name='billtemplate',
            name='thermal_print_density',
            field=models.IntegerField(default=50, help_text='Print density for thermal printers (0-100)'),
        ),
        migrations.CreateModel(
            name='CompanyBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Branding profile name (e.g., 'Main Company', 'Franchise A')", max_length=200)),
                ('logo', models.ImageField(blank=True, help_text='Company logo (will be optimized for thermal printing)', null=True, upload_to='company_logos/')),
                ('logo_width', models.IntegerField(default=200, help_text='Logo width in pixels for thermal printer')),
                ('logo_height', models.IntegerField(default=80, help_text='Logo height in pixels for thermal printer')),
                ('company_name', models.CharField(default='Zergo Distributors', max_length=200)),
                ('tagline', models.CharField(blank=True, help_text='Company tagline/slogan', max_length=200, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=200, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_id', models.CharField(blank=True, help_text='Tax/VAT registration number', max_length=50, null=True)),
                ('footer_line1', models.CharField(blank=True, default='Thank you for your business!', max_length=200, null=True)),
                ('footer_line2', models.CharField(blank=True, max_length=200, null=True)),
                ('footer_line3', models.CharField(blank=True, max_length=200, null=True)),
                ('show_logo', models.BooleanField(default=True, help_text='Show logo on receipts')),
                ('show_tagline', models.BooleanField(default=True)),
                ('show_address', models.BooleanField(default=True)),
                ('show_contact', models.BooleanField(default=True)),
                ('show_tax_id', models.BooleanField(default=False)),
                ('primary_color', models.CharField(default='#000000', help_text='Hex color code', max_length=7)),
                ('accent_color', models.CharField(default='#0066cc', help_text='Hex color code', max_length=7)),
                ('is_default', models.BooleanField(default=False, help_text='Default branding for new templates')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_brandings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Branding',
                'verbose_name_plural': 'Company Brandings',
                'db_table': 'company_branding',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AddField(
            model_name='billtemplate',
            name='branding',
            field=models.ForeignKey(blank=True, help_text='Company branding to use (leave blank to use individual settings)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='sales.companybranding'),
        ),
        migrations.CreateModel(
            name='PrinterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(help_text="Profile name (e.g., 'Office Printer', 'Mobile Bluetooth')", max_length=200)),
                ('printer_name', models.CharField(blank=True, help_text='Printer model/name', max_length=200, null=True)),
                ('bluetooth_address', models.CharField(blank=True, help_text='Bluetooth MAC address', max_length=100, null=True)),
                ('paper_size', models.CharField(choices=[('48mm', '48mm (1.89 inches)'), ('58mm', '58mm (2.28 inches)'), ('80mm', '80mm (3.15 inches)')], default='80mm', max_length=20)),
                ('paper_width_mm', models.IntegerField(default=80, help_text='Paper width in millimeters')),
                ('printable_width_mm', models.IntegerField(default=72, help_text='Printable area width in millimeters')),
                ('characters_per_line', models.IntegerField(default=32, help_text='Characters per line (usually 32 for 80mm, 24 for 58mm)')),
                ('print_density', models.IntegerField(choices=[(0, 'Lightest'), (25, 'Light'), (50, 'Normal'), (75, 'Dark'), (100, 'Darkest')], default=50, help_text='Print darkness (0-100)')),
                ('print_speed', models.IntegerField(default=5, help_text='Print speed (1-9, lower is faster)')),
                ('cut_behavior', models.CharField(choices=[('full', 'Full Cut'), ('partial', 'Partial Cut'), ('none', 'No Cut (Manual)')], default='partial', max_length=20)),
                ('cut_lines_after', models.IntegerField(default=3, help_text='Blank lines before cutting')),
                ('custom_init_commands', models.TextField(blank=True, help_text='Custom ESC/POS initialization commands (hex)', null=True)),
                ('custom_cut_commands', models.TextField(blank=True, help_text='Custom ESC/POS cut commands (hex)', null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Default printer profile')),
                ('is_favorite', models.BooleanField(default=False, help_text='Add to favorites list')),
                ('is_bluetooth', models.BooleanField(default=True, help_text='Bluetooth printer (for mobile)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printer_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Printer Profile',
                'verbose_name_plural': 'Printer Profiles',
                'db_table': 'printer_profiles',
                'ordering': ['-is_default', '-is_favorite', '-last_used_at'],
            },
        ),
    ]
