# Generated by Django 6.0 on 2026-01-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_alter_billtemplate_options_billtemplate_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billsettings',
            name='print_copies',
        ),
        migrations.AddField(
            model_name='billsettings',
            name='bill_print_copies',
            field=models.IntegerField(default=1, help_text='Number of copies to print for bills'),
        ),
        migrations.AddField(
            model_name='billsettings',
            name='field_receipt_print_copies',
            field=models.IntegerField(default=1, help_text='Number of copies to print for field receipts'),
        ),
        migrations.AddField(
            model_name='billsettings',
            name='payment_print_copies',
            field=models.IntegerField(default=1, help_text='Number of copies to print for payment receipts'),
        ),
        migrations.AddField(
            model_name='billsettings',
            name='return_print_copies',
            field=models.IntegerField(default=1, help_text='Number of copies to print for return receipts'),
        ),
        migrations.AlterField(
            model_name='billsettings',
            name='default_paper_size',
            field=models.CharField(choices=[('thermal_2inch', 'Thermal 2" (50.8mm)'), ('thermal_48mm', 'Thermal 48mm'), ('thermal_58mm', 'Thermal 58mm'), ('thermal_3inch', 'Thermal 3" (76.2mm)'), ('thermal_80mm', 'Thermal 80mm'), ('thermal_4inch', 'Thermal 4" (101.6mm)'), ('a4', 'A4 Paper (210mm)'), ('a5', 'A5 Paper (148mm)'), ('letter', 'Letter Size (8.5")')], default='thermal_80mm', max_length=20),
        ),
        migrations.AlterField(
            model_name='billtemplate',
            name='paper_size',
            field=models.CharField(choices=[('thermal_2inch', 'Thermal 2" (50.8mm)'), ('thermal_48mm', 'Thermal 48mm'), ('thermal_58mm', 'Thermal 58mm'), ('thermal_3inch', 'Thermal 3" (76.2mm)'), ('thermal_80mm', 'Thermal 80mm'), ('thermal_4inch', 'Thermal 4" (101.6mm)'), ('a4', 'A4 Paper (210mm)'), ('a5', 'A5 Paper (148mm)'), ('letter', 'Letter Size (8.5")')], max_length=20),
        ),
    ]
