# Generated by Django 6.0 on 2026-01-03 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_add_per_receipt_print_copies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billtemplate',
            name='branding',
        ),
        migrations.RemoveField(
            model_name='billtemplate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='companybranding',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='printerprofile',
            name='user',
        ),
        migrations.CreateModel(
            name='PrintManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(help_text="Profile name (e.g., 'Office Printer', 'Mobile Bluetooth', 'Invoice Template')", max_length=200)),
                ('is_default', models.BooleanField(default=False, help_text='Default print profile for this user')),
                ('is_active', models.BooleanField(default=True)),
                ('company_logo', models.ImageField(blank=True, help_text='Company logo (optimized for thermal printing)', null=True, upload_to='company_logos/')),
                ('logo_width', models.IntegerField(default=200, help_text='Logo width in pixels')),
                ('logo_height', models.IntegerField(default=80, help_text='Logo height in pixels')),
                ('show_logo', models.BooleanField(default=True, help_text='Show logo on receipts')),
                ('company_name', models.CharField(default='Zergo Distributors', max_length=200)),
                ('company_tagline', models.CharField(blank=True, help_text='Company tagline/slogan', max_length=200, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=200, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_id', models.CharField(blank=True, help_text='Tax/VAT registration number', max_length=50, null=True)),
                ('footer_line1', models.CharField(blank=True, default='Thank you for your business!', max_length=200, null=True)),
                ('footer_line2', models.CharField(blank=True, max_length=200, null=True)),
                ('footer_line3', models.CharField(blank=True, max_length=200, null=True)),
                ('show_tagline', models.BooleanField(default=True)),
                ('show_address', models.BooleanField(default=True)),
                ('show_contact', models.BooleanField(default=True)),
                ('show_tax_id', models.BooleanField(default=False)),
                ('receipt_type', models.CharField(choices=[('bill', 'Sales Bill/Invoice'), ('payment', 'Payment Receipt'), ('return_cash', 'Cash Return Receipt'), ('field_receipt', 'Field Cash Receipt')], default='bill', help_text='Type of receipt this profile is optimized for', max_length=20)),
                ('show_barcode', models.BooleanField(default=False, help_text='Show receipt number as barcode')),
                ('show_qr_code', models.BooleanField(default=True, help_text='Show QR code for verification')),
                ('qr_code_size', models.IntegerField(default=150, help_text='QR code size in pixels')),
                ('show_tax_breakdown', models.BooleanField(default=True)),
                ('show_discount_details', models.BooleanField(default=True)),
                ('show_payment_method', models.BooleanField(default=True)),
                ('show_sales_rep', models.BooleanField(default=True)),
                ('show_shop_location', models.BooleanField(default=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('si', 'Sinhala'), ('ta', 'Tamil')], default='en', help_text='Receipt language', max_length=5)),
                ('custom_header', models.TextField(blank=True, help_text='Custom header text (appears below company info)', null=True)),
                ('custom_footer', models.TextField(blank=True, help_text='Custom footer text (appears above footer lines)', null=True)),
                ('paper_size', models.CharField(choices=[('thermal_2inch', 'Thermal 2" (50.8mm)'), ('thermal_48mm', 'Thermal 48mm'), ('thermal_58mm', 'Thermal 58mm'), ('thermal_3inch', 'Thermal 3" (76.2mm)'), ('thermal_80mm', 'Thermal 80mm'), ('thermal_4inch', 'Thermal 4" (101.6mm)'), ('a4', 'A4 Paper (210mm)'), ('a5', 'A5 Paper (148mm)'), ('letter', 'Letter Size (8.5")')], default='thermal_80mm', help_text='Paper size (auto-configures fonts and layout)', max_length=20)),
                ('printer_name', models.CharField(blank=True, help_text='Printer model/name (for desktop printers)', max_length=200, null=True)),
                ('bluetooth_address', models.CharField(blank=True, help_text='Bluetooth MAC address (for mobile printers)', max_length=100, null=True)),
                ('is_bluetooth', models.BooleanField(default=True, help_text='Bluetooth thermal printer (mobile)')),
                ('print_density', models.IntegerField(choices=[(0, 'Lightest'), (25, 'Light'), (50, 'Normal'), (75, 'Dark'), (100, 'Darkest')], default=50, help_text='Print darkness (0-100)')),
                ('print_speed', models.IntegerField(default=5, help_text='Print speed (1-9, lower is faster)')),
                ('cut_behavior', models.CharField(choices=[('full', 'Full Cut'), ('partial', 'Partial Cut'), ('none', 'No Cut (Manual)')], default='partial', help_text='Paper cutting behavior', max_length=20)),
                ('feed_lines', models.IntegerField(default=3, help_text='Blank lines before cutting')),
                ('auto_print', models.BooleanField(default=False, help_text='Auto-print after transaction creation')),
                ('bill_print_copies', models.IntegerField(default=1, help_text='Copies to print for bills')),
                ('payment_print_copies', models.IntegerField(default=1, help_text='Copies to print for payment receipts')),
                ('return_print_copies', models.IntegerField(default=1, help_text='Copies to print for return receipts')),
                ('field_receipt_print_copies', models.IntegerField(default=1, help_text='Copies to print for field receipts')),
                ('margin_top', models.IntegerField(default=5, help_text='Top margin in mm (0 for default)')),
                ('margin_bottom', models.IntegerField(default=5, help_text='Bottom margin in mm (0 for default)')),
                ('margin_left', models.IntegerField(default=5, help_text='Left margin in mm (0 for default)')),
                ('margin_right', models.IntegerField(default=5, help_text='Right margin in mm (0 for default)')),
                ('font_size_header', models.IntegerField(default=0, help_text='Header font size in pt (0 for auto)')),
                ('font_size_body', models.IntegerField(default=0, help_text='Body font size in pt (0 for auto)')),
                ('font_size_footer', models.IntegerField(default=0, help_text='Footer font size in pt (0 for auto)')),
                ('custom_init_commands', models.TextField(blank=True, help_text='Custom ESC/POS initialization commands (hex)', null=True)),
                ('custom_cut_commands', models.TextField(blank=True, help_text='Custom ESC/POS cut commands (hex)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last time this profile was used', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Print Manager',
                'verbose_name_plural': 'Print Managers',
                'db_table': 'print_managers',
                'ordering': ['-is_default', '-last_used_at', 'profile_name'],
            },
        ),
        migrations.DeleteModel(
            name='BillSettings',
        ),
        migrations.DeleteModel(
            name='BillTemplate',
        ),
        migrations.DeleteModel(
            name='CompanyBranding',
        ),
        migrations.DeleteModel(
            name='PrinterProfile',
        ),
        migrations.AddConstraint(
            model_name='printmanager',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user', 'is_default', 'receipt_type'), name='one_default_per_user_per_receipt_type'),
        ),
    ]
