# Generated by Django 6.0 on 2026-01-06 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_unified_print_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnitem',
            name='is_damaged',
        ),
        migrations.RemoveField(
            model_name='returnitem',
            name='is_resellable',
        ),
        migrations.AlterField(
            model_name='return',
            name='cash_paid_by',
            field=models.ForeignKey(blank=True, help_text='User who paid cash to customer (sales rep or manager)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_settled_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='return',
            name='cash_receipt_number',
            field=models.CharField(blank=True, help_text='Cash payment voucher number (CPV-YYYYMMDD-XXX) - issued immediately when cash paid', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='return',
            name='field_cash_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='[DEPRECATED] No longer used', max_digits=10),
        ),
        migrations.AlterField(
            model_name='return',
            name='field_cash_given',
            field=models.BooleanField(default=False, help_text='[DEPRECATED] No longer used'),
        ),
        migrations.AlterField(
            model_name='return',
            name='field_cash_given_at',
            field=models.DateTimeField(blank=True, help_text='[DEPRECATED] No longer used', null=True),
        ),
        migrations.AlterField(
            model_name='return',
            name='field_cash_notes',
            field=models.TextField(blank=True, help_text='[DEPRECATED] No longer used', null=True),
        ),
        migrations.AlterField(
            model_name='return',
            name='field_receipt_number',
            field=models.CharField(blank=True, help_text='[DEPRECATED] No longer used', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='return',
            name='return_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='return',
            name='settlement_method',
            field=models.CharField(choices=[('cash', 'Cash Refund'), ('credit_note', 'Credit Note'), ('next_bill', 'Apply to Invoice')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='return',
            name='settlement_status',
            field=models.CharField(choices=[('unsettled', 'Awaiting Payment'), ('settled_cash', 'Cash Paid'), ('cancelled', 'Voucher Cancelled'), ('available', 'Credit Available'), ('partially_applied', 'Partially Applied'), ('fully_applied', 'Fully Applied')], default='unsettled', help_text='Tracks how the return is being settled', max_length=20),
        ),
    ]
