# Generated by Django 6.0 on 2026-01-12 19:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_purchase_system_initial'),
        ('sales', '0018_remove_resaleable_fields'),
        ('shops', '0002_shop_shop_photo_alter_shop_shop_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='returnitem',
            name='is_damaged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='returnitem',
            name='is_resellable',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ItemExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('exchange_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('exchange_reason', models.CharField(choices=[('damaged', 'Damaged Product'), ('expired', 'Expired Product'), ('defective', 'Defective Product'), ('quality', 'Quality Issue')], max_length=20)),
                ('exchange_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_exchanges', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchanges', to='shops.shop')),
            ],
            options={
                'verbose_name': 'Item Exchange',
                'verbose_name_plural': 'Item Exchanges',
                'db_table': 'item_exchanges',
                'ordering': ['-exchange_date'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returned_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('replacement_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_resellable', models.BooleanField(default=False, help_text='Can returned item be resold?')),
                ('non_resellable_quantity', models.DecimalField(decimal_places=2, default=0, help_text='Quantity that cannot be resold', max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('replacement_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replaced_in_exchanges', to='products.product')),
                ('returned_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returned_in_exchanges', to='products.product')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.itemexchange')),
            ],
            options={
                'verbose_name': 'Exchange Item',
                'verbose_name_plural': 'Exchange Items',
                'db_table': 'exchange_items',
            },
        ),
    ]
