# Generated by Django 6.0 on 2026-01-19 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_purchase_system_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='return',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='return',
            name='field_cash_amount',
        ),
        migrations.RemoveField(
            model_name='return',
            name='field_cash_given',
        ),
        migrations.RemoveField(
            model_name='return',
            name='field_cash_given_at',
        ),
        migrations.RemoveField(
            model_name='return',
            name='field_cash_notes',
        ),
        migrations.RemoveField(
            model_name='return',
            name='field_receipt_number',
        ),
        migrations.RemoveField(
            model_name='return',
            name='return_status',
        ),
        migrations.AddField(
            model_name='return',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Whether this return is locked by manager'),
        ),
        migrations.AddField(
            model_name='return',
            name='locked_at',
            field=models.DateTimeField(blank=True, help_text='When the return was locked', null=True),
        ),
        migrations.AddField(
            model_name='return',
            name='locked_by',
            field=models.ForeignKey(blank=True, help_text='Manager who locked this return', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_returns', to=settings.AUTH_USER_MODEL),
        ),
    ]
