# Generated by Django 6.0 on 2026-01-22 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_remove_return_approved_at_remove_return_approved_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='return',
            name='locked_at',
        ),
        migrations.RemoveField(
            model_name='return',
            name='locked_by',
        ),
        migrations.AddField(
            model_name='return',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='return',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='return',
            name='field_cash_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='[DEPRECATED] No longer used', max_digits=10),
        ),
        migrations.AddField(
            model_name='return',
            name='field_cash_given',
            field=models.BooleanField(default=False, help_text='[DEPRECATED] No longer used'),
        ),
        migrations.AddField(
            model_name='return',
            name='field_cash_given_at',
            field=models.DateTimeField(blank=True, help_text='[DEPRECATED] No longer used', null=True),
        ),
        migrations.AddField(
            model_name='return',
            name='field_cash_notes',
            field=models.TextField(blank=True, help_text='[DEPRECATED] No longer used', null=True),
        ),
        migrations.AddField(
            model_name='return',
            name='field_receipt_number',
            field=models.CharField(blank=True, help_text='[DEPRECATED] No longer used', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='return',
            name='return_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
