# Generated by Django 5.0 on 2026-01-22 14:06

from django.db import migrations, models
from django.utils import timezone


def approve_pending_returns(apps, schema_editor):
    """Auto-approve all pending returns for field operations workflow."""
    Return = apps.get_model('sales', 'Return')
    User = apps.get_model('accounts', 'User')
    
    # Get system user (admin) for approval
    try:
        admin_user = User.objects.filter(user_type='admin').first()
        if not admin_user:
            admin_user = User.objects.first()
    except:
        admin_user = None
    
    # Update all pending returns to approved
    pending_returns = Return.objects.filter(return_status='pending')
    count = pending_returns.count()
    
    if admin_user:
        pending_returns.update(
            return_status='approved',
            approved_by=admin_user,
            approved_at=timezone.now()
        )
    else:
        pending_returns.update(
            return_status='approved',
            approved_at=timezone.now()
        )
    
    if count > 0:
        print(f"✅ Auto-approved {count} pending returns for field operations")


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_remove_return_is_locked_remove_return_locked_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='return_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=20),
        ),
        migrations.RunPython(approve_pending_returns, reverse_code=migrations.RunPython.noop),
    ]
