# Generated by Django 5.0 on 2026-01-22 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_auto_approve_returns_for_field_ops'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='return',
            name='return_status',
        ),
        migrations.AddField(
            model_name='return',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Manager verified at end of day (locks return from changes)'),
        ),
        migrations.AddField(
            model_name='return',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='return',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_returns', to=settings.AUTH_USER_MODEL),
        ),
    ]
