# Generated by Django 5.0 on 2026-01-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0023_switch_to_verification_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionrecord',
            name='write_offs_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Bad debts written off (no commission)', max_digits=10),
        ),
    ]
