# Generated by Django 5.0 on 2026-01-23 15:10
# Modified for world-class settlement_status terminology

from django.db import migrations, models


def migrate_status_values(apps, schema_editor):
    """Migrate old values to new values AFTER field rename"""
    Bill = apps.get_model('sales', 'Bill')
    CommissionRecord = apps.get_model('sales', 'CommissionRecord')
    
    # Update Bill records
    Bill.objects.filter(settlement_status='unpaid').update(settlement_status='unsettled')
    Bill.objects.filter(settlement_status='partial').update(settlement_status='partial_settled')
    Bill.objects.filter(settlement_status='paid').update(settlement_status='settled')
    
    # Update CommissionRecord: pending→unsettled, paid→settled
    CommissionRecord.objects.filter(settlement_status='pending').update(settlement_status='unsettled')
    CommissionRecord.objects.filter(settlement_status='paid').update(settlement_status='settled')
    
    # Sale table may have been dropped (migration 0006) - handle gracefully
    try:
        from django.db import connection
        with connection.cursor() as cursor:
            cursor.execute("SELECT EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'sales')")
            if cursor.fetchone()[0]:
                Sale = apps.get_model('sales', 'Sale')
                Sale.objects.filter(settlement_status='unpaid').update(settlement_status='unsettled')
                Sale.objects.filter(settlement_status='partial').update(settlement_status='partial_settled')
                Sale.objects.filter(settlement_status='paid').update(settlement_status='settled')
    except Exception:
        pass


def reverse_status_values(apps, schema_editor):
    """Reverse migration - called after reverse rename"""
    Bill = apps.get_model('sales', 'Bill')
    CommissionRecord = apps.get_model('sales', 'CommissionRecord')
    
    Bill.objects.filter(payment_status='unsettled').update(payment_status='unpaid')
    Bill.objects.filter(payment_status='partial_settled').update(payment_status='partial')
    Bill.objects.filter(payment_status='settled').update(payment_status='paid')
    
    CommissionRecord.objects.filter(payment_status='unsettled').update(payment_status='pending')
    CommissionRecord.objects.filter(payment_status='settled').update(payment_status='paid')


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0024_commissionrecord_write_offs_amount_delete_payment'),
    ]

    operations = [
        # Step 1: Rename fields (preserves data AND column values)
        migrations.RenameField(
            model_name='bill',
            old_name='payment_status',
            new_name='settlement_status',
        ),
        migrations.RenameField(
            model_name='commissionrecord',
            old_name='payment_status',
            new_name='settlement_status',
        ),
        # Note: Sale model's table was dropped in migration 0006.
        # Sale RenameField/AlterField operations removed - handled in RunPython.
        
        # Step 2: Update existing values (unpaid→unsettled, etc.)
        migrations.RunPython(
            migrate_status_values,
            reverse_code=reverse_status_values,
        ),
        
        # Step 3: Update field definitions (choices and defaults)
        migrations.AlterField(
            model_name='bill',
            name='settlement_status',
            field=models.CharField(
                choices=[('unsettled', 'Unsettled'), ('partial_settled', 'Partially Settled'), ('settled', 'Settled')],
                default='unsettled',
                max_length=20
            ),
        ),
        migrations.AlterField(
            model_name='commissionrecord',
            name='settlement_status',
            field=models.CharField(
                choices=[('unsettled', 'Unsettled'), ('settled', 'Settled')],
                default='unsettled',
                max_length=20
            ),
        ),
    ]
