# Generated by Django 6.0 on 2026-01-23 17:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0026_commissionsettings_delete_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, help_text='Commission percentage (0-100)', max_digits=5)),
                ('effective_from', models.DateField(help_text='Date from which this rate applies')),
                ('effective_to', models.DateField(blank=True, help_text='Date until which this rate applies (null = current/active)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this the currently active rate?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Reason for rate change', null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_rates_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commission Rate History',
                'verbose_name_plural': 'Commission Rate History',
                'db_table': 'commission_rate_history',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='CommissionTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('bill_created', 'Bill Created'), ('payment_received', 'Payment Received'), ('return_processed', 'Return Processed'), ('writeoff_executed', 'Write-off Executed'), ('adjustment', 'Manual Adjustment')], max_length=20)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sales_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total bill amount (for bill_created)', max_digits=10)),
                ('collected_amount', models.DecimalField(decimal_places=2, default=0, help_text='Payment collected (for payment_received)', max_digits=10)),
                ('return_amount', models.DecimalField(decimal_places=2, default=0, help_text='Return amount (for return_processed)', max_digits=10)),
                ('applicable_rate', models.DecimalField(decimal_places=2, help_text='Commission rate at time of transaction', max_digits=5)),
                ('commission_earned', models.DecimalField(decimal_places=2, default=0, help_text='Commission earned from this transaction', max_digits=10)),
                ('running_balance', models.DecimalField(decimal_places=2, default=0, help_text='Cumulative commission balance after this transaction', max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_transactions', to='sales.bill')),
                ('sales_rep', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commission Transaction',
                'verbose_name_plural': 'Commission Transactions',
                'db_table': 'commission_transactions',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='commissiontransaction',
            index=models.Index(fields=['sales_rep', '-transaction_date'], name='commission__sales_r_4be903_idx'),
        ),
        migrations.AddIndex(
            model_name='commissiontransaction',
            index=models.Index(fields=['bill'], name='commission__bill_id_1fe8e1_idx'),
        ),
        migrations.AddIndex(
            model_name='commissiontransaction',
            index=models.Index(fields=['-transaction_date'], name='commission__transac_223c2f_idx'),
        ),
    ]
