# Generated by Django 6.0 on 2026-01-23 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0027_add_commission_rate_history_and_transactions'),
    ]

    operations = [
        # Remove old monthly batch commission system (replaced by real-time CommissionTransaction)
        migrations.DeleteModel(
            name='CommissionRecord',
        ),
    ]
