# Generated by Django 6.0 on 2026-01-23 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0028_remove_old_commission_record'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommissionSettings',
        ),
    ]
