# Generated by Django 5.0 on 2026-01-25 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_rename_to_sales_account_settlement'),
        ('sales', '0030_commission_transaction_uniqueness'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissiontransaction',
            name='settlement',
            field=models.ForeignKey(blank=True, help_text='Settlement that triggered this commission (for payment_received type)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_transactions', to='payments.salesaccountsettlement'),
        ),
    ]
