# Generated by Django 6.0 on 2026-01-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0033_add_return_ref_to_commission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commissionratehistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Commission Rate History', 'verbose_name_plural': 'Commission Rate History'},
        ),
        migrations.RemoveConstraint(
            model_name='commissiontransaction',
            name='unique_bill_commission',
        ),
        migrations.RemoveConstraint(
            model_name='commissiontransaction',
            name='unique_payment_commission',
        ),
        migrations.RemoveIndex(
            model_name='commissiontransaction',
            name='idx_commission_balance_calc',
        ),
        migrations.RemoveIndex(
            model_name='commissiontransaction',
            name='idx_commission_type_filter',
        ),
        migrations.AlterField(
            model_name='commissionratehistory',
            name='effective_from',
            field=models.DateTimeField(help_text='Date and time from which this rate applies'),
        ),
        migrations.AlterField(
            model_name='commissionratehistory',
            name='effective_to',
            field=models.DateTimeField(blank=True, help_text='Date and time until which this rate applies (null = current/active)', null=True),
        ),
        migrations.AlterField(
            model_name='commissiontransaction',
            name='transaction_type',
            field=models.CharField(choices=[('bill_created', 'Bill Created'), ('payment_received', 'Payment Received'), ('payment_cancelled', 'Payment Cancelled'), ('return_processed', 'Return Processed'), ('return_cancelled', 'Return Cancelled'), ('writeoff_executed', 'Write-off Executed'), ('adjustment', 'Manual Adjustment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='return',
            name='settlement_method',
            field=models.CharField(choices=[('cash', 'Cash Refund'), ('bill_adjustment', 'Bill Adjustment')], default='cash', max_length=20),
        ),
    ]
