# Generated by Django 6.0 on 2026-01-27 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0034_remove_payment_collected_by_remove_payment_sale_and_more'),
    ]

    operations = [
        # Payment table was already dropped in migration 0006 via raw SQL.
        # Use RunSQL with IF EXISTS to be safe on fresh schemas.
        migrations.RunSQL(
            sql='DROP TABLE IF EXISTS "payments" CASCADE;',
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
