# Generated by Django 6.0 on 2026-01-27 21:24

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_advancerequest_usermoneyaccount_moneytransaction_and_more'),
        ('sales', '0035_delete_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionPayoutSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly - Last day of month'), ('weekly', 'Weekly - Every Monday'), ('biweekly', 'Bi-weekly - Every 1st and 15th'), ('custom', 'Custom Date')], default='monthly', help_text='How often to process payouts', max_length=20)),
                ('payout_day_of_month', models.IntegerField(default=28, help_text='Day of month for payout (1-28 recommended, or 0 for last day)')),
                ('payout_time', models.TimeField(default='23:59:00', help_text='Time of day to execute payout (HH:MM:SS)')),
                ('next_custom_payout', models.DateTimeField(blank=True, help_text='Next scheduled custom payout date/time', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether automatic payouts are enabled')),
                ('last_run_date', models.DateTimeField(blank=True, help_text='When the last payout was executed', null=True)),
                ('next_run_date', models.DateTimeField(blank=True, help_text='When the next payout is scheduled', null=True)),
                ('minimum_payout_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum commission balance required to trigger payout (0 = no minimum)', max_digits=10)),
                ('auto_create_money_transactions', models.BooleanField(default=True, help_text='Automatically create money account transactions for payouts')),
                ('include_unpaid_only', models.BooleanField(default=True, help_text="Only credit commissions that haven't been paid to money account yet")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_schedules_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commission Payout Schedule',
                'verbose_name_plural': 'Commission Payout Schedules',
                'db_table': 'commission_payout_schedules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommissionPayoutHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('success', 'Completed Successfully'), ('partial', 'Partially Completed'), ('failed', 'Failed'), ('skipped', 'Skipped - No eligible payouts')], max_length=20)),
                ('total_users_processed', models.IntegerField(default=0)),
                ('total_amount_credited', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('successful_payouts', models.IntegerField(default=0)),
                ('failed_payouts', models.IntegerField(default=0)),
                ('skipped_payouts', models.IntegerField(default=0, help_text='Users below minimum threshold')),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('details', models.TextField(blank=True, help_text='JSON or text log of execution details')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0, help_text='How long the execution took')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_history', to='sales.commissionpayoutschedule')),
            ],
            options={
                'verbose_name': 'Commission Payout History',
                'verbose_name_plural': 'Commission Payout History',
                'db_table': 'commission_payout_history',
                'ordering': ['-execution_date'],
            },
        ),
        migrations.CreateModel(
            name='UserCommissionPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_balance', models.DecimalField(decimal_places=2, help_text='Commission balance at time of payout', max_digits=10)),
                ('amount_credited', models.DecimalField(decimal_places=2, help_text='Amount credited to money account', max_digits=10)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='success', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_payouts', to='sales.commissionpayouthistory')),
                ('money_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_payouts', to='accounts.moneytransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Commission Payout',
                'verbose_name_plural': 'User Commission Payouts',
                'db_table': 'user_commission_payouts',
                'ordering': ['-created_at'],
                'unique_together': {('history', 'user')},
            },
        ),
    ]
