# Generated by Django 6.0 on 2026-01-27 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0036_commissionpayoutschedule_commissionpayouthistory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commissionpayouthistory',
            options={'ordering': ['-execution_date'], 'verbose_name': 'Commission Payout Record', 'verbose_name_plural': 'Commission Payout Records'},
        ),
        migrations.AddField(
            model_name='commissionpayouthistory',
            name='executed_by',
            field=models.ForeignKey(blank=True, help_text='User who executed manual payout', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_payouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commissionpayouthistory',
            name='is_manual',
            field=models.BooleanField(default=False, help_text='Whether this was a manual payout or automated'),
        ),
        migrations.AddField(
            model_name='commissionpayouthistory',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this payout (for manual payouts)'),
        ),
        migrations.AddField(
            model_name='commissionpayouthistory',
            name='payout_number',
            field=models.CharField(default='CP-TEMP-001', editable=False, help_text='Commission Payout voucher number', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commissionpayouthistory',
            name='schedule',
            field=models.ForeignKey(blank=True, help_text='Schedule that triggered this payout (null for manual)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='execution_history', to='sales.commissionpayoutschedule'),
        ),
        migrations.AddIndex(
            model_name='commissionpayouthistory',
            index=models.Index(fields=['-execution_date'], name='commission__executi_e39fb6_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionpayouthistory',
            index=models.Index(fields=['schedule'], name='commission__schedul_fdc944_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionpayouthistory',
            index=models.Index(fields=['payout_number'], name='commission__payout__068ed5_idx'),
        ),
    ]
