# Generated by Django 5.0 on 2026-01-30 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0037_alter_commissionpayouthistory_options_and_more'),
    ]

    operations = [
    ]
