# Generated by Django 5.0 on 2026-01-30 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0038_add_payout_reference_to_commission_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissiontransaction',
            name='payout_history',
            field=models.ForeignKey(blank=True, help_text='Payout that triggered this adjustment (for payout clearing transactions)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_adjustments', to='sales.commissionpayouthistory'),
        ),
        migrations.AlterField(
            model_name='commissionpayouthistory',
            name='payout_number',
            field=models.CharField(default='CP-TEMP-001', editable=False, help_text='Commission Payout voucher number', max_length=50, unique=True),
        ),
    ]
