# Generated by Django 6.0 on 2026-01-30 17:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0039_commissiontransaction_payout_history_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FOCReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reset_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('reset_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_foc_received', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_foc_given', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_foc_returned', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_foc_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('avg_utilization', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_transactions', models.IntegerField(default=0)),
                ('total_products', models.IntegerField(default=0)),
                ('total_sales_reps', models.IntegerField(default=0)),
                ('company_accounts_snapshot', models.JSONField(help_text='Snapshot of all company FOC accounts at reset time')),
                ('product_summary_snapshot', models.JSONField(help_text='Product-wise FOC breakdown snapshot')),
                ('sales_rep_summary_snapshot', models.JSONField(help_text='Sales rep FOC usage snapshot')),
                ('transaction_types_breakdown', models.JSONField(help_text='Breakdown by transaction type')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reset_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='foc_resets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FOC Reset',
                'verbose_name_plural': 'FOC Resets',
                'db_table': 'foc_resets',
                'ordering': ['-reset_date'],
            },
        ),
        migrations.CreateModel(
            name='FOCResetTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=50)),
                ('transaction_date', models.DateTimeField()),
                ('company_name', models.CharField(max_length=200)),
                ('product_name', models.CharField(max_length=200)),
                ('product_size', models.CharField(max_length=100)),
                ('shop_name', models.CharField(blank=True, max_length=200, null=True)),
                ('sales_rep_name', models.CharField(blank=True, max_length=200, null=True)),
                ('foc_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shop_price_at_time', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('foc_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_transactions', to='sales.focreset')),
            ],
            options={
                'verbose_name': 'FOC Reset Transaction',
                'verbose_name_plural': 'FOC Reset Transactions',
                'db_table': 'foc_reset_transactions',
                'ordering': ['-transaction_date'],
                'indexes': [models.Index(fields=['reset', 'transaction_type'], name='foc_reset_t_reset_i_522a90_idx'), models.Index(fields=['reset', 'company_name'], name='foc_reset_t_reset_i_96f7ad_idx'), models.Index(fields=['reset', 'sales_rep_name'], name='foc_reset_t_reset_i_804595_idx')],
            },
        ),
    ]
