# Generated by Django 5.0 on 2026-01-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0040_focreset_focresettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='focresettransaction',
            name='bill_id',
            field=models.IntegerField(blank=True, help_text='Bill ID if from bill', null=True),
        ),
        migrations.AddField(
            model_name='focresettransaction',
            name='purchase_id',
            field=models.IntegerField(blank=True, help_text='Purchase ID if from purchase', null=True),
        ),
        migrations.AddField(
            model_name='focresettransaction',
            name='return_id',
            field=models.IntegerField(blank=True, help_text='Return ID if from return', null=True),
        ),
    ]
