# Generated by Django 6.0 on 2026-01-30 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0041_focresettransaction_bill_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseValueSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_value', models.DecimalField(decimal_places=2, help_text='Price per case (e.g., 2160.00)', max_digits=10)),
                ('effective_date', models.DateField(help_text='Date when this case value becomes effective')),
                ('is_active', models.BooleanField(default=True, help_text='Only one setting should be active at a time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_value_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case Value Setting',
                'verbose_name_plural': 'Case Value Settings',
                'db_table': 'eod_case_value_settings',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='DailyRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date the route was worked')),
                ('route', models.CharField(help_text="Route name(s) worked, e.g., 'Wattala & Sedawatta'", max_length=500)),
                ('notes', models.TextField(blank=True, help_text='Any additional notes about the day', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_routes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Route',
                'verbose_name_plural': 'Daily Routes',
                'db_table': 'eod_daily_routes',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
