# Generated by Django 5.0 on 2026-01-31 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0042_casevaluesetting_dailyroute'),
        ('shops', '0002_shop_shop_photo_alter_shop_shop_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='customer_name',
            field=models.CharField(blank=True, help_text='For unregistered customers', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='shops.shop'),
        ),
    ]
