# Generated by Django 5.0 on 2026-02-03 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_focvalueaccount_focvaluetransaction'),
        ('sales', '0044_return_customer_name_alter_return_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='printmanager',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Select a company to use their branding (logo, name, contact). Leave blank to use Distributor Profile.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.company'),
        ),
        migrations.AddField(
            model_name='printmanager',
            name='use_distributor_profile',
            field=models.BooleanField(default=True, help_text='Use Distributor Profile branding instead of company-specific branding'),
        ),
    ]
