# Generated by Django 5.0 on 2026-02-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0045_printmanager_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printmanager',
            name='show_website',
            field=models.BooleanField(default=False),
        ),
    ]
