# Generated by Django 6.0 on 2026-02-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0046_printmanager_show_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total COGS for this line = (quantity + foc_quantity) × unit_cost', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='billitem',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='FIFO weighted-average cost per unit at time of sale', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='printmanager',
            name='receipt_type',
            field=models.CharField(choices=[('bill', 'Sales Bill/Invoice'), ('payment', 'Payment Receipt'), ('return_cash', 'Cash Payment Voucher'), ('field_receipt', 'Field Cash Receipt')], default='bill', help_text='Type of receipt this profile is optimized for', max_length=20),
        ),
    ]
