# Generated by Django 6.0 on 2026-02-19 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0047_billitem_total_cost_billitem_unit_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='cost_breakdown',
            field=models.JSONField(blank=True, help_text='FIFO layer breakdown: [{source, reference, unit_cost, qty_consumed}, ...]', null=True),
        ),
    ]
