# Generated by Django 6.0 on 2026-02-20 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0048_billitem_cost_breakdown'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(help_text='Plan year (e.g., 2026)')),
                ('month', models.PositiveIntegerField(help_text='Plan month (1-12)')),
                ('area', models.CharField(blank=True, default='', help_text='Area/territory for this plan', max_length=200)),
                ('notes', models.TextField(blank=True, default='', help_text="Optional notes about this month's plan")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monthly Plan',
                'verbose_name_plural': 'Monthly Plans',
                'db_table': 'monthly_plans',
                'ordering': ['-year', '-month'],
                'unique_together': {('user', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyPlanDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField(help_text='Day of month (1-31)')),
                ('route', models.CharField(blank=True, default='', help_text="Route for this day, or 'Off' for a day off", max_length=500)),
                ('is_off', models.BooleanField(default=False, help_text='Whether this is a day off')),
                ('target_rd', models.IntegerField(default=0, help_text='R/D target (cases)')),
                ('target_pc', models.IntegerField(default=0, help_text='P/C target (productive calls / bill count)')),
                ('target_no', models.IntegerField(default=0, help_text='N/O target (new outlets)')),
                ('target_purchase', models.IntegerField(default=0, help_text='Purchase target (from company)')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='sales.monthlyplan')),
            ],
            options={
                'verbose_name': 'Monthly Plan Day',
                'verbose_name_plural': 'Monthly Plan Days',
                'db_table': 'monthly_plan_days',
                'ordering': ['day'],
                'unique_together': {('plan', 'day')},
            },
        ),
    ]
