# Generated by Django 6.0 on 2025-12-19 22:15

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        # Create StockKeepingUnit model
        migrations.CreateModel(
            name='StockKeepingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(help_text='Auto-generated: e.g., MAX-250ML-90', max_length=50, unique=True)),
                ('size', models.CharField(choices=[('250ML', '250ML'), ('500ML', '500ML'), ('750ML', '750ML'), ('1000ML', '1000ML (1L)'), ('1500ML', '1500ML (1.5L)'), ('2200ML', '2200ML (2.2L)')], max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit from supplier', max_digits=10)),
                ('quantity_in_stock', models.IntegerField(default=0, help_text='Total bottles in stock')),
                ('minimum_stock_level', models.IntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='products.company')),
            ],
            options={
                'verbose_name': 'Stock Keeping Unit (SKU)',
                'verbose_name_plural': 'Stock Keeping Units (SKUs)',
                'db_table': 'stock_keeping_units',
                'ordering': ['company', 'size', 'unit_price'],
                'unique_together': {('company', 'size', 'unit_price')},
            },
        ),
        
        # Create PurchaseOrder model
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=50, unique=True)),
                ('order_date', models.DateField()),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ordered', 'Ordered'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='products.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'purchase_orders',
                'ordering': ['-order_date', '-po_number'],
            },
        ),
        
        # Create PurchaseOrderItem model
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packs', models.IntegerField(default=0, help_text='Number of packs/cartons')),
                ('bottles_per_pack', models.IntegerField(default=0, help_text='Bottles in each pack')),
                ('total_bottles', models.IntegerField(help_text='Total bottles (packs × bottles per pack)')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('value_before_discount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('received_quantity', models.IntegerField(default=0, help_text='Actual bottles received')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.purchaseorder')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_items', to='products.stockkeepingunit')),
            ],
            options={
                'db_table': 'purchase_order_items',
            },
        ),
        
        # Remove old Product fields
        migrations.RemoveField(
            model_name='product',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wholesale_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit_of_measure',
        ),
        migrations.RemoveField(
            model_name='product',
            name='current_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='minimum_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tax_percentage',
        ),
        
        # Rename unit_price to selling_price temporarily
        migrations.RenameField(
            model_name='product',
            old_name='unit_price',
            new_name='selling_price',
        ),
        
        # Add new Product fields
        migrations.AddField(
            model_name='product',
            name='flavor',
            field=models.CharField(blank=True, help_text='e.g., Orange, Nexta, Cola, Cream Soda', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=23.00, help_text='Discount % given to shops', max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.ForeignKey(help_text="SKU that this product's inventory is tracked under", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.stockkeepingunit'),
        ),
        
        # Update StockMovement to reference SKU instead of Product
        migrations.RemoveField(
            model_name='stockmovement',
            name='product',
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='sku',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='products.stockkeepingunit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('purchase', 'Purchase/Stock In'), ('sale', 'Sale/Stock Out'), ('adjustment', 'Adjustment'), ('return', 'Return from Shop'), ('damage', 'Damage/Wastage')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.IntegerField(help_text='Positive for stock in, negative for stock out'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='previous_quantity',
            field=models.IntegerField(default=0, help_text='Stock before this movement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='new_quantity',
            field=models.IntegerField(default=0, help_text='Stock after this movement'),
            preserve_default=False,
        ),
        
        # Update Product model ordering
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['company', 'sku__size', 'flavor']},
        ),
    ]
