# Generated by Django 6.0 on 2025-12-21 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_add_monthly_stock_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='sales_rep',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='product',
        ),
        migrations.RemoveConstraint(
            model_name='monthlystockcount',
            name='unique_count_date_product',
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='foc_bottles',
            field=models.IntegerField(default=0, help_text='Free of Charge bottles received from company'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='received_foc',
            field=models.IntegerField(default=0, help_text='Actual FOC bottles received'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='foc_quantity',
            field=models.IntegerField(default=0, help_text='Free of Charge quantity (tracked separately)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Discount % given to shops (default 10%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(help_text='e.g., 250ML Max Orange', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.ForeignKey(blank=True, help_text="SKU that this product's inventory is tracked under", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.stockkeepingunit'),
        ),
        migrations.AlterField(
            model_name='stockkeepingunit',
            name='marked_price',
            field=models.DecimalField(decimal_places=2, help_text='Marked retail price', max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockkeepingunit',
            name='sku_code',
            field=models.CharField(help_text='Auto-generated: e.g., MAX-250ML-100', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('purchase', 'Purchase/Stock In'), ('sale', 'Sale/Stock Out'), ('adjustment', 'Adjustment'), ('return', 'Return from Shop'), ('damage', 'Damage/Wastage'), ('foc_in', 'FOC Received from Company'), ('foc_out', 'FOC Given to Shop')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reference_number',
            field=models.CharField(blank=True, help_text='PO number, Bill number, etc.', max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='monthlystockcount',
            unique_together={('count_date', 'product')},
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.DeleteModel(
            name='SaleItem',
        ),
    ]
