# Generated by Django 6.0 on 2025-12-23 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_sale_created_by_remove_sale_sales_rep_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockkeepingunit',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='stockkeepingunit',
            name='company',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='sku',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['company', 'product_name']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='flavor',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='flavor',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='foc_quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='marked_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Marked retail price', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='minimum_stock_level',
            field=models.IntegerField(default=50, help_text='Minimum stock alert level'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_in_stock',
            field=models.IntegerField(default=0, help_text='Current stock quantity'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('250ML', '250ML'), ('500ML', '500ML'), ('750ML', '750ML'), ('1000ML', '1000ML (1L)'), ('1500ML', '1500ML (1.5L)'), ('2200ML', '2200ML (2.2L)')], default='500ML', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='po_items', to='products.product'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='products.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(help_text='e.g., Max Orange 500ml', max_length=200),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('purchase', 'Purchase/Stock In'), ('sale', 'Sale/Stock Out'), ('adjustment', 'Stock Count Adjustment'), ('return', 'Return from Shop'), ('damage', 'Damage/Wastage'), ('foc_in', 'FOC Received from Company'), ('foc_out', 'FOC Given to Shop')], max_length=20),
        ),
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_date', models.DateTimeField(auto_now_add=True, help_text='When the count was performed')),
                ('system_stock', models.IntegerField(help_text='Stock in system before count')),
                ('physical_count', models.IntegerField(help_text='Actual physical count')),
                ('variance', models.IntegerField(help_text='Difference: Physical - System')),
                ('adjustment_reason', models.TextField(blank=True, help_text='Reason for variance (e.g., damage, theft, counting error)', null=True)),
                ('stock_updated', models.BooleanField(default=False, help_text='Whether product stock was updated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('counted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_counts', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_counts', to='products.product')),
            ],
            options={
                'db_table': 'stock_counts',
                'ordering': ['-count_date'],
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='stock_count',
            field=models.ForeignKey(blank=True, help_text='Link to stock count if this is an adjustment', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.stockcount'),
        ),
        migrations.DeleteModel(
            name='MonthlyStockCount',
        ),
        migrations.DeleteModel(
            name='StockKeepingUnit',
        ),
    ]
