# Generated by Django 6.0 on 2025-12-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_stockkeepingunit_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['display_order', 'product_name']},
        ),
        migrations.AddField(
            model_name='product',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Order in which product appears in lists (lower number appears first)'),
        ),
    ]
