# Generated by Django 6.0 on 2025-12-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_options_product_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='company_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=23.0, help_text='Discount % we get from company on shop price (default 23%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='company_foc_buy',
            field=models.IntegerField(default=12, help_text='Number of bottles to buy to get FOC from company (e.g., 12)'),
        ),
        migrations.AddField(
            model_name='product',
            name='company_foc_free',
            field=models.IntegerField(default=1, help_text='Number of free bottles from company (e.g., 1 free for every 12)'),
        ),
        migrations.AddField(
            model_name='product',
            name='shop_foc_buy',
            field=models.IntegerField(default=12, help_text='Number of bottles shop must buy to get FOC (e.g., 12)'),
        ),
        migrations.AddField(
            model_name='product',
            name='shop_foc_free',
            field=models.IntegerField(default=1, help_text='Number of free bottles given to shop (e.g., 1 free for every 12)'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('opening_balance', 'Opening Balance'), ('purchase', 'Purchase/Stock In'), ('sale', 'Sale/Stock Out'), ('adjustment', 'Stock Count Adjustment'), ('return', 'Return from Shop'), ('damage', 'Damage/Wastage'), ('foc_in', 'FOC Received from Company'), ('foc_out', 'FOC Given to Shop')], max_length=20),
        ),
    ]
