# Generated by Django 6.0 on 2025-12-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_company_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bottles_per_pack',
            field=models.IntegerField(default=24, help_text='Number of bottles in one pack/case (default 24)'),
        ),
    ]
