# Generated by Django 6.0 on 2025-12-25 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_bottles_per_pack'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('opening_balance', 'Opening Balance'), ('purchase', 'Purchase/Stock In'), ('sale', 'Sale/Stock Out'), ('adjustment', 'Stock Count Adjustment'), ('return', 'Return from Shop'), ('damage', 'Damage/Wastage'), ('foc_in', 'FOC Received from Company'), ('foc_out', 'FOC Given to Shop'), ('status_adjustment', 'Status Adjustment (Damaged/Used/etc)')], max_length=20),
        ),
        migrations.CreateModel(
            name='ProductStatusAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_type', models.CharField(choices=[('damaged', 'Damaged'), ('expired', 'Expired'), ('used', 'Used/Consumed'), ('lost', 'Lost/Missing'), ('sample', 'Sample/Giveaway'), ('returned_to_company', 'Returned to Company'), ('other', 'Other')], max_length=30)),
                ('quantity', models.IntegerField(help_text='Number of units with this status')),
                ('reason', models.TextField(help_text='Detailed reason for this adjustment')),
                ('reference_number', models.CharField(blank=True, help_text='Reference number if any', max_length=50, null=True)),
                ('stock_updated', models.BooleanField(default=True, help_text='Whether stock was deducted')),
                ('previous_stock', models.IntegerField(help_text='Stock before adjustment')),
                ('new_stock', models.IntegerField(help_text='Stock after adjustment')),
                ('adjustment_date', models.DateTimeField(auto_now_add=True)),
                ('adjusted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_adjustments', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_adjustments', to='products.product')),
            ],
            options={
                'db_table': 'product_status_adjustments',
                'ordering': ['-adjustment_date'],
            },
        ),
    ]
