# Generated by Django 6.0 on 2026-01-02 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_stockmovement_movement_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('return_date', models.DateTimeField(auto_now_add=True)),
                ('sent_date', models.DateField(blank=True, help_text='Date items were sent to company', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent to Company'), ('credited', 'Credit Received'), ('replaced', 'Replacement Received'), ('rejected', 'Rejected by Company')], default='pending', max_length=20)),
                ('settlement_type', models.CharField(choices=[('credit_note', 'Credit Note'), ('replacement', 'Replacement Products'), ('cash_refund', 'Cash Refund')], default='credit_note', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total value of returned items', max_digits=10)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, help_text='Actual credit/refund received', max_digits=10)),
                ('credit_note_number', models.CharField(blank=True, help_text="Company's credit note reference", max_length=100, null=True)),
                ('reason', models.TextField(help_text='Reason for return (damaged, expired, etc.)')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_returns', to='products.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_company_returns', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_company_returns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Return',
                'verbose_name_plural': 'Company Returns',
                'db_table': 'company_returns',
                'ordering': ['-return_date'],
            },
        ),
        migrations.CreateModel(
            name='CompanyReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity returned to company', max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=10)),
                ('total_value', models.DecimalField(decimal_places=2, help_text='Total value', max_digits=10)),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('company_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.companyreturn')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
            options={
                'db_table': 'company_return_items',
            },
        ),
    ]
