# Generated by Django 6.0 on 2026-01-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_companyreturn_companyreturnitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('opening_balance', 'Opening Balance'), ('purchase', 'Purchase/Stock In'), ('sale', 'Sale/Stock Out'), ('adjustment', 'Stock Count Adjustment'), ('return', 'Return from Shop'), ('exchange', 'Product Exchange'), ('damage', 'Damage/Wastage'), ('foc_in', 'FOC Received from Company'), ('foc_out', 'FOC Given to Shop'), ('status_adjustment', 'Status Adjustment (Damaged/Used/etc)')], max_length=20),
        ),
    ]
