# Generated by Django 6.0 on 2026-01-09 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_stockmovement_movement_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productstatusadjustment',
            name='adjustment_number',
            field=models.CharField(blank=True, default='', editable=False, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='productstatusadjustment',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='productstatusadjustment',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productstatusadjustment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_adjustments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productstatusadjustment',
            name='new_stock',
            field=models.IntegerField(default=0, help_text='Stock after adjustment'),
        ),
        migrations.AlterField(
            model_name='productstatusadjustment',
            name='previous_stock',
            field=models.IntegerField(default=0, help_text='Stock before adjustment'),
        ),
        migrations.AlterField(
            model_name='productstatusadjustment',
            name='status_type',
            field=models.CharField(choices=[('damaged', 'Damaged'), ('expired', 'Expired'), ('used', 'Used/Consumed'), ('lost', 'Lost/Missing'), ('sample', 'Sample/Giveaway'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='productstatusadjustment',
            name='stock_updated',
            field=models.BooleanField(default=False, help_text='Whether stock was deducted'),
        ),
    ]
