# Generated by Django 6.0 on 2026-01-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_productstatusadjustment_adjustment_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='non_resellable_stock',
            field=models.IntegerField(default=0, help_text='Damaged/expired/lost items not available for sale'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_in_stock',
            field=models.IntegerField(default=0, help_text='Current stock quantity available for sale'),
        ),
        migrations.AlterField(
            model_name='productstatusadjustment',
            name='adjustment_number',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
