# Generated by Django 6.0 on 2026-01-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_add_non_resellable_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='non_resellable_stock',
        ),
        migrations.AddField(
            model_name='product',
            name='non_resaleable_stock',
            field=models.IntegerField(default=0, help_text='Non-resaleable stock (damaged/expired/quarantined)'),
        ),
        migrations.AddField(
            model_name='productstatusadjustment',
            name='stock_action',
            field=models.CharField(choices=[('move_to_non_resaleable', 'Move to Non-Resaleable Stock'), ('reduce_completely', 'Reduce Stock Completely'), ('record_only', 'Record Only (No Stock Change)')], default='move_to_non_resaleable', help_text='How to handle stock when adjustment is approved', max_length=30),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='stock_type',
            field=models.CharField(choices=[('resaleable', 'Resaleable'), ('non_resaleable', 'Non-Resaleable')], default='resaleable', help_text='Type of stock being moved', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_in_stock',
            field=models.IntegerField(default=0, help_text='Resaleable stock quantity (available for sale)'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('opening_balance', 'Opening Balance'), ('purchase', 'Purchase/Stock In'), ('sale', 'Sale/Stock Out'), ('adjustment', 'Stock Count Adjustment'), ('return', 'Return from Shop'), ('exchange', 'Product Exchange'), ('damage', 'Damage/Wastage'), ('foc_in', 'FOC Received from Company'), ('foc_out', 'FOC Given to Shop'), ('status_adjustment', 'Status Adjustment (Damaged/Used/etc)'), ('non_resaleable_in', 'Transfer to Non-Resaleable'), ('non_resaleable_out', 'Dispose Non-Resaleable'), ('non_resaleable_restore', 'Restore to Resaleable')], max_length=25),
        ),
    ]
