# Generated by Django 6.0 on 2026-01-09 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_add_non_resaleable_stock_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstatusadjustment',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_adjustments', to='products.product'),
        ),
        migrations.AlterField(
            model_name='productstatusadjustment',
            name='quantity',
            field=models.IntegerField(default=0, help_text='Legacy: Number of units (use items for multi-item)'),
        ),
        migrations.CreateModel(
            name='ProductStatusAdjustmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Number of units with this status')),
                ('stock_updated', models.BooleanField(default=False, help_text='Whether stock was updated')),
                ('previous_resaleable', models.IntegerField(default=0, help_text='Resaleable stock before adjustment')),
                ('new_resaleable', models.IntegerField(default=0, help_text='Resaleable stock after adjustment')),
                ('previous_non_resaleable', models.IntegerField(default=0, help_text='Non-resaleable stock before adjustment')),
                ('new_non_resaleable', models.IntegerField(default=0, help_text='Non-resaleable stock after adjustment')),
                ('adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.productstatusadjustment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustment_items', to='products.product')),
            ],
            options={
                'db_table': 'product_status_adjustment_items',
                'ordering': ['id'],
                'unique_together': {('adjustment', 'product')},
            },
        ),
    ]
