# Generated by Django 6.0 on 2026-01-09 13:19

from django.db import migrations


def convert_existing_adjustments(apps, schema_editor):
    """Convert existing single-item adjustments to multi-item format"""
    ProductStatusAdjustment = apps.get_model('products', 'ProductStatusAdjustment')
    ProductStatusAdjustmentItem = apps.get_model('products', 'ProductStatusAdjustmentItem')
    
    # Find all adjustments with a product (old format)
    old_adjustments = ProductStatusAdjustment.objects.filter(product__isnull=False)
    
    converted = 0
    for adjustment in old_adjustments:
        # Check if item already exists (prevent duplicates)
        if not ProductStatusAdjustmentItem.objects.filter(adjustment=adjustment).exists():
            # Create corresponding item
            ProductStatusAdjustmentItem.objects.create(
                adjustment=adjustment,
                product=adjustment.product,
                quantity=adjustment.quantity,
                stock_updated=adjustment.stock_updated,
                previous_resaleable=adjustment.previous_stock if adjustment.previous_stock else 0,
                new_resaleable=adjustment.new_stock if adjustment.new_stock else 0,
                previous_non_resaleable=0,  # Not tracked in old format
                new_non_resaleable=0  # Not tracked in old format
            )
            converted += 1
    
    print(f"Converted {converted} existing adjustments to multi-item format")


def reverse_conversion(apps, schema_editor):
    """Remove items created during conversion"""
    ProductStatusAdjustmentItem = apps.get_model('products', 'ProductStatusAdjustmentItem')
    # Delete all items (reversing the migration)
    count = ProductStatusAdjustmentItem.objects.count()
    ProductStatusAdjustmentItem.objects.all().delete()
    print(f"Removed {count} adjustment items during migration reversal")


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_productstatusadjustment_product_and_more'),
    ]

    operations = [
        migrations.RunPython(convert_existing_adjustments, reverse_conversion),
    ]
