# Generated by Django 6.0 on 2026-01-12 19:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_convert_existing_adjustments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('opening_balance', 'Opening Balance'), ('purchase', 'Purchase/Stock In'), ('purchase_return', 'Purchase Return'), ('sale', 'Sale/Stock Out'), ('adjustment', 'Stock Count Adjustment'), ('return', 'Return from Shop'), ('exchange', 'Product Exchange'), ('damage', 'Damage/Wastage'), ('foc_in', 'FOC Received from Company'), ('foc_out', 'FOC Given to Shop'), ('status_adjustment', 'Status Adjustment (Damaged/Used/etc)'), ('non_resaleable_in', 'Transfer to Non-Resaleable'), ('non_resaleable_out', 'Dispose Non-Resaleable'), ('non_resaleable_restore', 'Restore to Resaleable')], max_length=25),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grn_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('grn_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date goods were received')),
                ('invoice_date', models.DateField(blank=True, help_text='Supplier invoice date', null=True)),
                ('supplier_invoice_number', models.CharField(blank=True, help_text="Supplier's invoice number", max_length=100, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, help_text='Total before discount', max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total discount', max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Net amount payable', max_digits=12)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid')], default='unpaid', max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('stock_updated', models.BooleanField(default=False, help_text='Whether stock has been updated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='products.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_purchases', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(blank=True, help_text='Who physically received the goods', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchase (GRN)',
                'verbose_name_plural': 'Purchases (GRN)',
                'db_table': 'purchases',
                'ordering': ['-grn_date', '-grn_number'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packs', models.IntegerField(default=0, help_text='Number of packs/cartons received')),
                ('bottles_per_pack', models.IntegerField(default=0, help_text='Bottles per pack')),
                ('quantity', models.IntegerField(default=0, help_text='Total bottles received (packs × bottles_per_pack)')),
                ('foc_quantity', models.IntegerField(default=0, help_text='FOC bottles received (added to main stock)')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, help_text='Price per bottle', max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, help_text='Total for this line (FOC not included)', max_digits=12)),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='products.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.purchase')),
            ],
            options={
                'db_table': 'purchase_items',
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('return_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date return was created')),
                ('sent_date', models.DateField(blank=True, help_text='Date items sent to supplier', null=True)),
                ('return_reason', models.CharField(choices=[('damaged', 'Damaged Product'), ('expired', 'Expired Product'), ('quality', 'Quality Issue'), ('wrong_product', 'Wrong Product Delivered'), ('excess_qty', 'Excess Quantity'), ('other', 'Other')], max_length=20)),
                ('detailed_reason', models.TextField(default='', help_text='Detailed explanation of return')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('sent', 'Sent to Supplier'), ('credited', 'Credit Received'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('settlement_type', models.CharField(choices=[('credit_note', 'Credit Note'), ('replacement', 'Replacement Products'), ('refund', 'Cash Refund')], default='credit_note', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total value of returned items', max_digits=12)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, help_text='Actual credit/refund received', max_digits=12)),
                ('credit_note_number', models.CharField(blank=True, help_text="Supplier's credit note reference", max_length=100, null=True)),
                ('stock_updated', models.BooleanField(default=False, help_text='Whether stock has been reduced')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_purchase_returns', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_returns', to='products.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_purchase_returns', to=settings.AUTH_USER_MODEL)),
                ('purchase', models.ForeignKey(blank=True, help_text='Reference GRN if returning against specific purchase', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='products.purchase')),
            ],
            options={
                'verbose_name': 'Purchase Return',
                'verbose_name_plural': 'Purchase Returns',
                'db_table': 'purchase_returns',
                'ordering': ['-return_date', '-pr_number'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, help_text='Number of bottles being returned')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, help_text='Original purchase price per bottle', max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, help_text='Total value', max_digits=12)),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('item_reason', models.TextField(blank=True, help_text='Specific reason for this item', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_return_items', to='products.product')),
                ('purchase_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.purchasereturn')),
            ],
            options={
                'db_table': 'purchase_return_items',
            },
        ),
    ]
