# Generated by Django 6.0 on 2026-01-12 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_purchase_system_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchase_order',
            field=models.ForeignKey(blank=True, help_text='Reference PO if this GRN is against a PO', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grns', to='products.purchaseorder'),
        ),
    ]
