# Generated by Django 5.0 on 2026-01-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_sync_purchase_order_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='loose_bottles',
            field=models.IntegerField(default=0, help_text='Loose bottles received (not in full packs)'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='loose_bottles',
            field=models.IntegerField(default=0, help_text='Loose bottles (not in full packs)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('220ML', '220ML'), ('250ML', '250ML'), ('500ML', '500ML'), ('750ML', '750ML'), ('1000ML', '1000ML (1L)'), ('1500ML', '1500ML (1.5L)'), ('2200ML', '2200ML (2.2L)')], default='500ML', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='quantity',
            field=models.IntegerField(default=0, help_text='Total bottles received (packs × bottles_per_pack + loose)'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='total_bottles',
            field=models.IntegerField(help_text='Total bottles (packs × bottles per pack + loose)'),
        ),
    ]
