# Generated by Django 6.0 on 2026-01-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_purchaseitem_loose_bottles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereturn',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total discount amount', max_digits=12),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='replacement_expected',
            field=models.BooleanField(default=False, help_text='Expecting replacement products'),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='replacement_notes',
            field=models.TextField(blank=True, help_text='Notes about replacement', null=True),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='replacement_received',
            field=models.BooleanField(default=False, help_text='Replacement products received'),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='replacement_received_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Actual replacement value received', max_digits=12),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='replacement_value_expected',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Expected replacement value', max_digits=12),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='return_type',
            field=models.CharField(choices=[('expired', 'Expired Product'), ('damaged', 'Damaged Product')], default='damaged', help_text='Main return category', max_length=20),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total before discount', max_digits=12),
        ),
    ]
