# Generated by Django 5.0 on 2026-01-15 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_purchasereturn_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereturn',
            name='replacement_grn',
            field=models.ForeignKey(blank=True, help_text='GRN containing replacement products', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_for_returns', to='products.purchase'),
        ),
    ]
