# Generated by Django 5.0 on 2026-01-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_add_replacement_grn_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereturn',
            name='approved_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount approved by company for settlement', max_digits=12),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='settlement_status',
            field=models.CharField(choices=[('pending', 'Pending Settlement'), ('partial', 'Partially Settled'), ('fully_settled', 'Fully Settled')], default='pending', help_text='Settlement completion status', max_length=20),
        ),
    ]
