# Generated by Django 5.0 on 2026-01-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_add_settlement_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='company_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount % we get from company (second tier on invoice price)', max_digits=5),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='shop_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount % given to shops (first tier)', max_digits=5),
        ),
    ]
