# Generated by Django 5.0 on 2026-01-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_add_two_tier_discount_to_purchase_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereturnitem',
            name='company_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Distributor discount % at time of return', max_digits=5),
        ),
        migrations.AddField(
            model_name='purchasereturnitem',
            name='marked_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Marked price at time of return', max_digits=10),
        ),
        migrations.AddField(
            model_name='purchasereturnitem',
            name='shop_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Invoice discount % at time of return', max_digits=5),
        ),
        migrations.AlterField(
            model_name='purchasereturnitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Final distributor price per bottle (after both discounts)', max_digits=10),
        ),
    ]
