# Generated by Django 5.0 on 2026-01-15 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_add_discount_breakdown_to_purchase_return_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, help_text='Opening balance (amount we owe to company at start)', max_digits=12)),
                ('opening_date', models.DateField(blank=True, help_text='Date when opening balance was recorded', null=True)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, help_text='Current outstanding balance (auto-calculated from transactions)', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='products.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_company_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Account',
                'verbose_name_plural': 'Company Accounts',
                'db_table': 'company_accounts',
            },
        ),
        migrations.CreateModel(
            name='CompanyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('opening_balance', 'Opening Balance'), ('purchase', 'Purchase/GRN'), ('return', 'Purchase Return'), ('payment', 'Payment to Company'), ('adjustment', 'Manual Adjustment')], max_length=20)),
                ('transaction_date', models.DateTimeField()),
                ('reference_number', models.CharField(help_text='GRN number, PR number, payment number, etc.', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive for purchases, negative for payments/returns', max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='products.companyaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_company_transactions', to=settings.AUTH_USER_MODEL)),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_transactions', to='products.purchase')),
                ('purchase_return', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_transactions', to='products.purchasereturn')),
            ],
            options={
                'verbose_name': 'Company Transaction',
                'verbose_name_plural': 'Company Transactions',
                'db_table': 'company_transactions',
                'ordering': ['-transaction_date', '-id'],
            },
        ),
    ]
