# Generated by Django 5.0 on 2026-01-16 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_add_company_account_system'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyaccount',
            options={'ordering': ['company__company_name'], 'verbose_name': 'Company Account', 'verbose_name_plural': 'Company Accounts'},
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='company_discount_percentage',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='shop_discount_percentage',
        ),
        migrations.RemoveField(
            model_name='purchasereturnitem',
            name='company_discount_percentage',
        ),
        migrations.RemoveField(
            model_name='purchasereturnitem',
            name='marked_price',
        ),
        migrations.RemoveField(
            model_name='purchasereturnitem',
            name='shop_discount_percentage',
        ),
        migrations.AddField(
            model_name='companyaccount',
            name='opening_notes',
            field=models.TextField(blank=True, help_text='Notes about the opening balance', null=True),
        ),
        migrations.AddField(
            model_name='companytransaction',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Cheque number, bank transfer ID, etc.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companytransaction',
            name='settled_against',
            field=models.ForeignKey(blank=True, help_text='The transaction this settles (for offset settlements)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settling_transactions', to='products.companytransaction'),
        ),
        migrations.AddField(
            model_name='companytransaction',
            name='settlement_method',
            field=models.CharField(blank=True, choices=[('credit', 'On Credit'), ('cash', 'Cash'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank Transfer'), ('grn_offset', 'GRN Offset'), ('return_offset', 'Return Offset')], default='credit', help_text='How this transaction was settled', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='companytransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='companyaccount',
            name='company',
            field=models.OneToOneField(help_text='The company this account belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='account', to='products.company'),
        ),
        migrations.AlterField(
            model_name='companytransaction',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the transaction', null=True),
        ),
        migrations.AlterField(
            model_name='companytransaction',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes', null=True),
        ),
        migrations.AlterField(
            model_name='companytransaction',
            name='transaction_date',
            field=models.DateTimeField(help_text='Date and time of transaction'),
        ),
        migrations.AlterField(
            model_name='companytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('opening_balance', 'Opening Balance'), ('purchase', 'Purchase/GRN'), ('return', 'Purchase Return'), ('payment', 'Payment to Company'), ('adjustment', 'Manual Adjustment')], help_text='Type of transaction', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchasereturnitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Original purchase price per bottle', max_digits=10),
        ),
    ]
