# Generated by Django 5.0 on 2026-01-16 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_alter_companyaccount_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='company_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Company/Distributor discount %', max_digits=5),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='invoice_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price after shop discount', max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='marked_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Marked/list price per bottle', max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='shop_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Shop/Invoice discount %', max_digits=5),
        ),
        migrations.AddField(
            model_name='purchasereturnitem',
            name='company_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Company/Distributor discount %', max_digits=5),
        ),
        migrations.AddField(
            model_name='purchasereturnitem',
            name='invoice_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price after shop discount', max_digits=10),
        ),
        migrations.AddField(
            model_name='purchasereturnitem',
            name='marked_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Marked/list price per bottle', max_digits=10),
        ),
        migrations.AddField(
            model_name='purchasereturnitem',
            name='shop_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Shop/Invoice discount %', max_digits=5),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Legacy field - total discount amount', max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Legacy field - total discount %', max_digits=5),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Final price per bottle after all discounts', max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchasereturnitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Final price per bottle after all discounts', max_digits=10),
        ),
    ]
