# Generated by Django 5.0 on 2026-01-17 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_companypayment_paymentallocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereturn',
            name='company_approved_date',
            field=models.DateField(blank=True, help_text='Date company approved the return', null=True),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='sent_at',
            field=models.DateTimeField(blank=True, help_text='When sent to supplier', null=True),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='sent_by',
            field=models.ForeignKey(blank=True, help_text='User who sent to supplier', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_purchase_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When company approval was recorded', null=True),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='User who approved company response', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_purchase_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent_to_supplier', 'Sent to Supplier'), ('company_approved', 'Approved by Company'), ('settled', 'Settled'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
