# Generated by Django 5.0 on 2026-01-17 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_update_purchase_return_workflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseReturnSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_method', models.CharField(choices=[('replacement', 'Replacement GRN'), ('credit_note', 'Credit Note'), ('refund', 'Cash Refund')], help_text='Method of settlement', max_length=20)),
                ('settlement_amount', models.DecimalField(decimal_places=2, help_text='Amount settled via this method', max_digits=12)),
                ('credit_note_number', models.CharField(blank=True, help_text='Credit note reference number', max_length=100, null=True)),
                ('refund_reference', models.CharField(blank=True, help_text='Refund transaction reference', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_return_settlements', to=settings.AUTH_USER_MODEL)),
                ('purchase_return', models.ForeignKey(help_text='Parent purchase return', on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='products.purchasereturn')),
                ('replacement_grn', models.ForeignKey(blank=True, help_text='GRN used for replacement settlement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlement_for_returns', to='products.purchase')),
            ],
            options={
                'verbose_name': 'Purchase Return Settlement',
                'verbose_name_plural': 'Purchase Return Settlements',
                'db_table': 'purchase_return_settlements',
                'ordering': ['-created_at'],
            },
        ),
    ]
