# Generated by Django 6.0 on 2026-01-18 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_purchasereturnsettlement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereturnsettlement',
            name='cash_receipt_number',
            field=models.CharField(blank=True, help_text='Receipt/voucher number for cash received', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasereturnsettlement',
            name='cash_received_date',
            field=models.DateField(blank=True, help_text='Date cash was actually received from supplier', null=True),
        ),
        migrations.AddField(
            model_name='purchasereturnsettlement',
            name='cash_verification_notes',
            field=models.TextField(blank=True, help_text='Notes about cash verification/receipt', null=True),
        ),
        migrations.AddField(
            model_name='purchasereturnsettlement',
            name='cash_verified_by',
            field=models.ForeignKey(blank=True, help_text='User who verified cash receipt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_cash_refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companytransaction',
            name='settlement_method',
            field=models.CharField(blank=True, choices=[('credit', 'On Credit'), ('cash', 'Cash'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank Transfer'), ('grn_offset', 'GRN Offset'), ('return_offset', 'Return Offset'), ('pending_settlement', 'Pending Settlement')], default='credit', help_text='How this transaction was settled', max_length=20, null=True),
        ),
    ]
