# Generated by Django 6.0 on 2026-01-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_add_cash_audit_fields_and_fix_settlement_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasereturnsettlement',
            name='settlement_method',
            field=models.CharField(choices=[('replacement', 'Replacement GRN'), ('refund', 'Cash Refund')], help_text='Method of settlement', max_length=20),
        ),
    ]
