# Generated by Django 5.0 on 2026-01-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_remove_credit_note_settlement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('opening_balance', 'Opening Balance'), ('purchase', 'Purchase/GRN'), ('return', 'Purchase Return'), ('payment', 'Payment to Company'), ('settlement', 'Settlement Receipt'), ('adjustment', 'Manual Adjustment')], help_text='Type of transaction', max_length=20),
        ),
    ]
