# Generated by Django 6.0 on 2026-01-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_add_settlement_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyreturnitem',
            name='company_return',
        ),
        migrations.RemoveField(
            model_name='companyreturnitem',
            name='product',
        ),
        migrations.AddField(
            model_name='stockcount',
            name='count_number',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='CompanyReturn',
        ),
        migrations.DeleteModel(
            name='CompanyReturnItem',
        ),
    ]
