# Generated by Django 5.0 on 2026-01-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_remove_company_returns_and_fix_stockcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(default='Sri Lanka', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of the company', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, help_text='Company logo', null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='company',
            name='primary_color',
            field=models.CharField(blank=True, help_text='Hex color code (e.g., #FF0000)', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='registration_number',
            field=models.CharField(blank=True, help_text='Business registration number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='secondary_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='tagline',
            field=models.CharField(blank=True, help_text='Company slogan or tagline', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_id',
            field=models.CharField(blank=True, help_text='Tax Identification Number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
