# Generated by Django 5.0 on 2026-01-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_company_city_company_country_company_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasereturn',
            name='settlement_type',
            field=models.CharField(choices=[('replacement', 'Replacement Products'), ('refund', 'Cash Refund')], default='refund', max_length=20),
        ),
    ]
