# Generated by Django 6.0 on 2026-01-27 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_remove_credit_note_option'),
        ('sales', '0035_delete_payment'),
        ('shops', '0002_shop_shop_photo_alter_shop_shop_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FOCValueAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_foc_received_value', models.DecimalField(decimal_places=2, default=0, help_text='FOC value received from company at opening (shop_price basis)', max_digits=12)),
                ('opening_foc_given_value', models.DecimalField(decimal_places=2, default=0, help_text='FOC value given to shops at opening (shop_price basis)', max_digits=12)),
                ('opening_date', models.DateField(blank=True, help_text='Date when opening balances were recorded', null=True)),
                ('opening_notes', models.TextField(blank=True, help_text='Notes about opening FOC balances', null=True)),
                ('total_foc_received_value', models.DecimalField(decimal_places=2, default=0, help_text='Total FOC value received from company (including opening)', max_digits=12)),
                ('total_foc_given_value', models.DecimalField(decimal_places=2, default=0, help_text='Total FOC value given to shops (including opening)', max_digits=12)),
                ('net_foc_value', models.DecimalField(decimal_places=2, default=0, help_text='Positive = received more, Negative = gave more than received', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(help_text='The company this FOC account belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='foc_account', to='products.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_foc_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FOC Value Account',
                'verbose_name_plural': 'FOC Value Accounts',
                'db_table': 'foc_value_accounts',
                'ordering': ['company__company_name'],
            },
        ),
        migrations.CreateModel(
            name='FOCValueTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(editable=False, help_text='Auto-generated: FOC-YYYYMMDD-###', max_length=50, unique=True)),
                ('transaction_type', models.CharField(choices=[('foc_received', 'FOC Received from Company'), ('foc_given', 'FOC Given to Shop'), ('return_foc_restored', 'Return FOC Restored'), ('implicit_foc', 'Implicit FOC (Below Shop Price)'), ('adjustment', 'Manual Adjustment')], help_text='Type of FOC transaction', max_length=30)),
                ('transaction_date', models.DateTimeField(help_text='When this FOC transaction occurred')),
                ('foc_quantity', models.DecimalField(decimal_places=2, help_text='Quantity of FOC (bottles)', max_digits=10)),
                ('shop_price_at_time', models.DecimalField(decimal_places=2, help_text='Shop price at time of transaction (for historical accuracy)', max_digits=10)),
                ('foc_value', models.DecimalField(decimal_places=2, help_text='Calculated: foc_quantity × shop_price_at_time', max_digits=12)),
                ('reference_number', models.CharField(help_text='Source document number (GRN#, Bill#, Return#)', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this transaction', null=True)),
                ('is_archived', models.BooleanField(default=False, help_text='Archived transactions (after account reset)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill_item', models.ForeignKey(blank=True, help_text='Link to bill item (if from old bill system)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foc_transactions', to='sales.billitem')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_foc_transactions', to=settings.AUTH_USER_MODEL)),
                ('foc_account', models.ForeignKey(help_text='FOC account this transaction belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='products.focvalueaccount')),
                ('product', models.ForeignKey(help_text='Product for which FOC was given/received', on_delete=django.db.models.deletion.PROTECT, related_name='foc_transactions', to='products.product')),
                ('purchase_item', models.ForeignKey(blank=True, help_text='Link to purchase item (if foc_received)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foc_transactions', to='products.purchaseitem')),
                ('return_item', models.ForeignKey(blank=True, help_text='Link to return item (if return_foc_restored)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foc_transactions', to='sales.returnitem')),
                ('sales_rep', models.ForeignKey(blank=True, help_text='Sales rep who gave FOC (for foc_given transactions)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foc_transactions_as_rep', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(blank=True, help_text='Shop that received FOC (for foc_given transactions)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foc_transactions', to='shops.shop')),
            ],
            options={
                'verbose_name': 'FOC Value Transaction',
                'verbose_name_plural': 'FOC Value Transactions',
                'db_table': 'foc_value_transactions',
                'ordering': ['-transaction_date', '-id'],
                'indexes': [models.Index(fields=['-transaction_date', 'foc_account'], name='foc_value_t_transac_0cdb93_idx'), models.Index(fields=['transaction_type', 'foc_account'], name='foc_value_t_transac_7ed67c_idx'), models.Index(fields=['product', 'transaction_type'], name='foc_value_t_product_bf567f_idx'), models.Index(fields=['is_archived'], name='foc_value_t_is_arch_7e0419_idx')],
            },
        ),
    ]
