# Generated by Django 5.0 on 2026-02-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_focvalueaccount_focvaluetransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo_receipt',
            field=models.ImageField(blank=True, help_text='Logo optimized for thermal receipts (Black & White, 200x80px)', null=True, upload_to='company_logos/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, help_text='Primary company logo', null=True, upload_to='company_logos/'),
        ),
    ]
