# Generated by Django 6.0 on 2026-02-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_company_logo_receipt_alter_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total cost for this movement = abs(quantity) × unit_cost', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Cost per unit at time of movement (effective cost including FOC spread)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('opening_balance', 'Opening Balance'), ('purchase', 'Purchase/Stock In'), ('purchase_return', 'Purchase Return'), ('sale', 'Sale/Stock Out'), ('adjustment', 'Stock Count Adjustment'), ('return', 'Return from Shop'), ('exchange', 'Product Exchange'), ('damage', 'Damage/Wastage'), ('foc_in', 'FOC Received from Company'), ('foc_out', 'FOC Given to Shop'), ('status_adjustment', 'Status Adjustment (Damaged/Used/etc)'), ('non_resaleable_in', 'Transfer to Non-Resaleable'), ('non_resaleable_out', 'Dispose Non-Resaleable'), ('non_resaleable_restore', 'Restore to Resaleable'), ('return_to_company', 'Return to Company/Supplier')], max_length=25),
        ),
    ]
