# Generated by Django 6.0 on 2026-02-18 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_stockmovement_total_cost_stockmovement_unit_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FIFOCostLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_cost', models.DecimalField(decimal_places=4, help_text='Cost per unit for this layer', max_digits=10)),
                ('original_quantity', models.IntegerField(help_text='Original quantity when layer was created')),
                ('remaining_quantity', models.IntegerField(help_text='Remaining unconsumed quantity in this layer')),
                ('layer_source', models.CharField(choices=[('purchase', 'Purchase/GRN'), ('opening_balance', 'Opening Balance'), ('return', 'Sales Return'), ('exchange_in', 'Exchange IN'), ('adjustment', 'Stock Adjustment')], max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='GRN number, OB reference, Return number, etc.', max_length=50, null=True)),
                ('is_exhausted', models.BooleanField(default=False, help_text='True when remaining_quantity reaches 0')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_layers', to='products.product')),
            ],
            options={
                'db_table': 'fifo_cost_layers',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['product', 'is_exhausted', 'created_at'], name='fifo_cost_l_product_951c8c_idx')],
            },
        ),
    ]
