# Generated by Django 6.0 on 2026-02-24 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('products', '0042_fifocostlayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='global_product',
            field=models.ForeignKey(blank=True, help_text='Link to global product catalog (shared across all distributors)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_products', to='catalog.globalproduct'),
        ),
    ]
